Repository omniosorg/illumos-omnios, pull requests merged in 2018-12, with the labels that each got.

#340 Joyent merge/2018120701
  README.OmniOS
  usr/src/cmd/bhyve/block_if.c
  usr/src/cmd/bhyve/block_if.h
  usr/src/cmd/bhyve/fwctl.c
  usr/src/cmd/bhyve/gdb.c
  usr/src/cmd/bhyve/pci_ahci.c
  usr/src/cmd/bhyve/pci_nvme.c
  usr/src/cmd/bhyve/pci_virtio_block.c
  usr/src/uts/i86pc/io/vmm/vm/vm_glue.h
  usr/src/uts/i86pc/io/vmm/vmm.c
  usr/src/uts/i86pc/io/vmm/vmm_sol_dev.c
  usr/src/uts/i86pc/io/vmm/vmm_sol_vm.c
  usr/src/uts/i86pc/io/vmm/vmm_zsd.c
  usr/src/uts/i86pc/sys/vmm_impl.h
Labels: backport-todo, upstream-merge

#345 Upstream merge joyent_merge/2018121901
  README.OmniOS
  usr/src/uts/common/fs/zfs/metaslab.c
  usr/src/uts/common/fs/zfs/sys/metaslab_impl.h
  usr/src/uts/i86pc/io/vmm/vmm_sol_dev.c
Labels: backport-todo, upstream-merge

#346 OS-7151 ZFS loading and unloading metaslabs at audible frequency (r151028)
  usr/src/uts/common/fs/zfs/metaslab.c
  usr/src/uts/common/fs/zfs/sys/metaslab_impl.h
Labels: backport-PR

#347 Upstream merge/2018122001
  exception_lists/cstyle
  exception_lists/hdrchk
  exception_lists/keywords
  usr/src/Makefile.master
  usr/src/boot/Makefile.version
  usr/src/boot/sys/boot/common/disk.c
  usr/src/boot/sys/boot/common/part.c
  usr/src/boot/sys/boot/common/part.h
  usr/src/cmd/zpool/zpool_main.c
  usr/src/common/zfs/zpool_prop.c
  usr/src/lib/libc/port/gen/getentropy.c
  usr/src/lib/libc/port/gen/l3.c
  usr/src/lib/libc/port/mapfile-vers
  usr/src/lib/libc/port/sys/getrandom.c
  usr/src/lib/libzfs/common/libzfs_pool.c
  usr/src/lib/pylibbe/Makefile.com
  usr/src/lib/pylibbe/amd64/Makefile
  usr/src/lib/pylibbe/i386/Makefile
  usr/src/lib/pylibbe/py3/Makefile
  usr/src/lib/pysolaris/Makefile.com
  usr/src/lib/pysolaris/amd64/Makefile
  usr/src/lib/pysolaris/i386/Makefile
  usr/src/lib/pysolaris/py3/Makefile
  usr/src/lib/pyzfs/Makefile.com
  usr/src/lib/pyzfs/amd64/Makefile
  usr/src/lib/pyzfs/i386/Makefile
  usr/src/lib/pyzfs/py3/Makefile
  usr/src/man/man1m/zpool.1m
  usr/src/man/man2/Makefile
  usr/src/man/man2/getrandom.2
  usr/src/pkg/manifests/system-kernel.man2.inc
  usr/src/pkg/manifests/system-test-zfstest.mf
  usr/src/test/zfs-tests/runfiles/delphix.run
  usr/src/test/zfs-tests/runfiles/omnios.run
  usr/src/test/zfs-tests/runfiles/openindiana.run
  usr/src/test/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_tempname.ksh
  usr/src/test/zfs-tests/tests/functional/cli_root/zpool_import/zpool_import_014_pos.ksh
  usr/src/tools/cw/cw.1onbld
  usr/src/tools/cw/cw.c
  usr/src/tools/env/illumos.sh
  usr/src/tools/env/omnios-illumos-gate.sh
  usr/src/tools/env/omnios-illumos-omnios.sh
  usr/src/uts/common/fs/zfs/spa.c
  usr/src/uts/common/fs/zfs/spa_config.c
  usr/src/uts/common/fs/zfs/zfs_ioctl.c
  usr/src/uts/common/os/sysent.c
  usr/src/uts/common/sys/fs/zfs.h
  usr/src/uts/common/sys/random.h
  usr/src/uts/common/syscall/getrandom.c
Labels: upstream-merge

#349 Upstream merge/2018122601
  usr/src/cmd/boot/Makefile
  usr/src/cmd/boot/mbr/Makefile
  usr/src/cmd/boot/mbr/mbr.c
  usr/src/cmd/rmformat/rmf_slice.c
  usr/src/cmd/ztest/ztest.c
  usr/src/common/crypto/aes/aes_impl.h
  usr/src/common/crypto/aes/aes_modes.c
  usr/src/common/crypto/modes/gcm.c
  usr/src/common/crypto/modes/modes.h
  usr/src/lib/pkcs11/libpkcs11/common/metaCrypt.c
  usr/src/lib/pkcs11/libsoftcrypto/Makefile.com
  usr/src/lib/pkcs11/libsoftcrypto/Makefile.targ
  usr/src/lib/pkcs11/libsoftcrypto/amd64/Makefile
  usr/src/lib/pkcs11/libsoftcrypto/common/mapfile-vers
  usr/src/lib/pkcs11/pkcs11_kernel/common/kernelDecrypt.c
  usr/src/lib/pkcs11/pkcs11_kernel/common/kernelEncrypt.c
  usr/src/lib/pkcs11/pkcs11_kernel/common/kernelGlobal.h
  usr/src/lib/pkcs11/pkcs11_kernel/common/kernelUtil.c
  usr/src/lib/pkcs11/pkcs11_softtoken/Makefile.com
  usr/src/lib/pkcs11/pkcs11_softtoken/common/softAESCrypt.c
  usr/src/lib/pkcs11/pkcs11_softtoken/common/softCrypt.h
  usr/src/lib/pkcs11/pkcs11_softtoken/common/softDecryptUtil.c
  usr/src/lib/pkcs11/pkcs11_softtoken/common/softEncrypt.c
  usr/src/lib/pkcs11/pkcs11_softtoken/common/softEncryptUtil.c
  usr/src/lib/pkcs11/pkcs11_softtoken/common/softKeystore.c
  usr/src/lib/pkcs11/pkcs11_softtoken/common/softSignUtil.c
  usr/src/lib/pkcs11/pkcs11_softtoken/common/softSlotToken.c
  usr/src/lib/pkcs11/pkcs11_softtoken/common/softVerifyUtil.c
  usr/src/pkg/manifests/system-boot-real-mode.mf
  usr/src/pkg/manifests/system-kernel.mf
  usr/src/psm/stand/bootblks/ufs/i386/Makefile
  usr/src/psm/stand/bootblks/ufs/i386/mboot.S
  usr/src/test/crypto-tests/tests/common/cryptotest.h
  usr/src/test/crypto-tests/tests/common/cryptotest_kcf.c
  usr/src/test/crypto-tests/tests/common/cryptotest_pkcs.c
  usr/src/test/crypto-tests/tests/modes/aes/Makefile.subdirs
  usr/src/test/crypto-tests/tests/modes/aes/ccm/aes_ccm.c
  usr/src/uts/common/crypto/io/aes.c
  usr/src/uts/common/crypto/io/crypto.c
  usr/src/uts/common/crypto/io/dprov.c
  usr/src/uts/common/fs/zfs/sys/dmu.h
  usr/src/uts/common/fs/zfs/sys/zfs_rlock.h
  usr/src/uts/common/fs/zfs/sys/zfs_znode.h
  usr/src/uts/common/fs/zfs/zfs_rlock.c
  usr/src/uts/common/fs/zfs/zfs_vnops.c
  usr/src/uts/common/fs/zfs/zfs_znode.c
  usr/src/uts/common/fs/zfs/zvol.c
  usr/src/uts/common/inet/mi.c
  usr/src/uts/common/io/comstar/lu/stmf_sbd/sbd_zvol.c
  usr/src/uts/intel/ia32/os/syscall.c
Labels: upstream-merge
