Repository omniosorg/illumos-omnios, pull requests merged in 2018-10, with the labels that each got.

#279 Updating for r151028
  usr/src/tools/env/omnios-illumos-gate.sh
  usr/src/tools/env/omnios-illumos-omnios.sh
Labels: review

#280 Upstream merge joyent_merge/2018100401
  README.OmniOS
  usr/src/lib/brand/lx/lx_brand/common/signal.c
  usr/src/lib/brand/lx/lx_brand/sys/lx_misc.h
  usr/src/uts/common/brand/lx/os/lx_brand.c
  usr/src/uts/common/brand/lx/sys/lx_brand.h
  usr/src/uts/common/brand/lx/syscall/lx_poll.c
  usr/src/uts/i86pc/io/viona/viona.c
Labels: review, upstream-merge

#281 Backports/2018100401
  usr/src/lib/brand/lx/lx_brand/common/signal.c
  usr/src/lib/brand/lx/lx_brand/sys/lx_misc.h
  usr/src/uts/common/brand/lx/os/lx_brand.c
  usr/src/uts/common/brand/lx/sys/lx_brand.h
  usr/src/uts/i86pc/io/viona/viona.c
Labels: review

#284 Upstream merge/2018100501
  usr/src/Makefile
  usr/src/Makefile.master
  usr/src/Makefile.master.64
  usr/src/boot/sys/boot/i386/libi386/pxe.h
  usr/src/cmd/dtrace/test/tst/common/Makefile
  usr/src/cmd/dtrace/test/tst/common/pid/tst.gcc.c
  usr/src/cmd/dtrace/test/tst/common/pid/tst.gcc.d
  usr/src/cmd/zdb/zdb.c
  usr/src/cmd/ztest/ztest.c
  usr/src/common/mapfiles/gen/Makefile
  usr/src/lib/libkmf/libkmf/Makefile.com
  usr/src/man/man3lib/libkmf.3lib
  usr/src/pkg/manifests/system-dtrace-tests.mf
  usr/src/test/os-tests/tests/file-locking/Makefile
  usr/src/tools/cw/Makefile
  usr/src/tools/cw/cw.1onbld
  usr/src/tools/cw/cw.c
  usr/src/tools/env/illumos.sh
  usr/src/tools/scripts/nightly.sh
  usr/src/uts/common/fs/zfs/aggsum.c
  usr/src/uts/common/fs/zfs/arc.c
  usr/src/uts/common/fs/zfs/metaslab.c
  usr/src/uts/common/fs/zfs/spa.c
  usr/src/uts/common/fs/zfs/spa_misc.c
  usr/src/uts/common/fs/zfs/sys/spa.h
  usr/src/uts/common/fs/zfs/sys/vdev_impl.h
  usr/src/uts/common/fs/zfs/vdev.c
Labels: review, upstream-merge

#283 virtio_block - Pass unhandled options through to blockif (r151028)
  usr/src/cmd/bhyve/pci_virtio_block.c
Labels: backport-PR, review

#282 BHYVE: Allow generic block_if options for virtio disks
  usr/src/cmd/bhyve/pci_virtio_block.c
Labels: backport-todo, review

#288 Add config/parallel to svc:/system/filesystem/local
  usr/src/cmd/svc/milestone/fs-local
  usr/src/cmd/svc/milestone/local-fs.xml
  usr/src/lib/libzfs/common/libzfs_mount.c
Labels: backport-PR

#289 Upstream merge upstream_merge/2018101101
  exception_lists/wscheck
  usr/src/Makefile.master
  usr/src/cmd/boot/scripts/create_ramdisk.ksh
  usr/src/cmd/ldapcachemgr/Makefile
  usr/src/cmd/nscd/Makefile
  usr/src/cmd/zfs/zfs_main.c
  usr/src/lib/fm/topo/libtopo/common/hc.c
  usr/src/lib/fm/topo/libtopo/common/libtopo.h
  usr/src/lib/fm/topo/libtopo/common/mapfile-vers
  usr/src/lib/fm/topo/libtopo/common/topo_hc.h
  usr/src/lib/fm/topo/libtopo/common/topo_mod.map
  usr/src/lib/fm/topo/libtopo/common/topo_subr.c
  usr/src/lib/fm/topo/modules/common/smbios/smbios_enum.c
  usr/src/lib/libnsl/Makefile.com
  usr/src/man/man1m/zfs-program.1m
  usr/src/man/man1m/zfs.1m
  usr/src/pkg/manifests/system-test-zfstest.mf
  usr/src/test/zfs-tests/runfiles/delphix.run
  usr/src/test/zfs-tests/runfiles/omnios.run
  usr/src/test/zfs-tests/runfiles/openindiana.run
  usr/src/test/zfs-tests/tests/functional/cli_root/zfs_program/Makefile
  usr/src/test/zfs-tests/tests/functional/cli_root/zfs_program/cleanup.ksh
  usr/src/test/zfs-tests/tests/functional/cli_root/zfs_program/setup.ksh
  usr/src/test/zfs-tests/tests/functional/cli_root/zfs_program/zfs_program_json.ksh
  usr/src/tools/cw/cw.c
  usr/src/tools/scripts/nightly.sh
  usr/src/uts/common/io/qede/579xx/drivers/ecore/ecore_dcbx.c
  usr/src/uts/common/io/qede/579xx/drivers/ecore/ecore_mcp.c
  usr/src/uts/common/io/qede/579xx/drivers/ecore/ecore_phy.c
  usr/src/uts/common/io/qede/qede_gld.c
  usr/src/uts/common/io/vioif/vioif.c
  usr/src/uts/common/sys/smbios.h
Labels: upstream-merge

#294 New thread-name APIs should be exposed under ILLUMOS_0.28 (r151028)
  usr/src/lib/libc/port/mapfile-vers
Labels: backport-PR

#296 Upstream merge joyent_merge/2018101801
  README.OmniOS
  usr/src/cmd/bhyve/pci_hostbridge.c
  usr/src/cmd/nscd/cache.c
  usr/src/cmd/ps/ps.c
  usr/src/cmd/sgs/elfdump/common/gen_struct_layout.c
  usr/src/cmd/sgs/elfdump/common/struct_layout.h
  usr/src/cmd/sgs/elfdump/common/struct_layout_amd64.c
  usr/src/cmd/sgs/elfdump/common/struct_layout_i386.c
  usr/src/cmd/sgs/elfdump/common/struct_layout_sparc.c
  usr/src/cmd/sgs/elfdump/common/struct_layout_sparcv9.c
  usr/src/lib/libc/port/threads/thr.c
  usr/src/uts/common/brand/lx/os/lx_ptrace.c
  usr/src/uts/i86pc/io/viona/viona.c
Labels: upstream-merge

#297 Upstream merge backports/2018101901
  usr/src/cmd/beadm/beadm.c
  usr/src/cmd/boot/bootadm/bootadm.c
  usr/src/cmd/boot/bootadm/bootadm_loader.c
  usr/src/lib/libbe/common/be_activate.c
  usr/src/lib/libbe/common/be_list.c
  usr/src/lib/libbe/common/be_utils.c
  usr/src/lib/libbe/common/libbe.h
  usr/src/lib/libbe/common/libbe_priv.h
  usr/src/lib/pylibbe/common/libbe_py.c
  usr/src/uts/common/brand/lx/os/lx_ptrace.c
Labels: backport-PR

#300 9925 Update hwdata to 2018.10.25 (r151028)
  usr/src/data/hwdata/pci.ids
  usr/src/data/hwdata/usb.ids
Labels: backport-PR

#302 9935 update tzdata to 2018g (r151028)
  usr/src/data/zoneinfo/africa
  usr/src/data/zoneinfo/antarctica
  usr/src/data/zoneinfo/asia
  usr/src/data/zoneinfo/australasia
  usr/src/data/zoneinfo/backward
  usr/src/data/zoneinfo/etcetera
  usr/src/data/zoneinfo/europe
  usr/src/data/zoneinfo/northamerica
  usr/src/data/zoneinfo/southamerica
  usr/src/data/zoneinfo/systemv
  usr/src/data/zoneinfo/zone.tab.txt
  usr/src/data/zoneinfo/zone_sun.tab
  usr/src/pkg/manifests/system-data-zoneinfo.mf
Labels: backport-PR
