Repository omniosorg/illumos-omnios, pull requests merged in 2018-11, with the labels that each got.

#306 QLC driver updates (r151028)
  usr/src/cmd/mdb/common/modules/qlc/qlc.c
  usr/src/pkg/manifests/driver-network-qlc.mf
  usr/src/uts/common/Makefile.files
  usr/src/uts/common/io/comstar/port/qlt/2400.c
  usr/src/uts/common/io/comstar/port/qlt/2500.c
  usr/src/uts/common/io/comstar/port/qlt/2700.c
  usr/src/uts/common/io/comstar/port/qlt/8100.c
  usr/src/uts/common/io/comstar/port/qlt/8300fc.c
  usr/src/uts/common/io/comstar/port/qlt/qlt.c
  usr/src/uts/common/io/comstar/port/qlt/qlt.h
  usr/src/uts/common/io/comstar/port/qlt/qlt_dma.c
  usr/src/uts/common/io/comstar/port/qlt/qlt_dma.h
  usr/src/uts/common/io/comstar/port/qlt/qlt_ioctl.h
  usr/src/uts/common/io/comstar/port/qlt/qlt_open.h
  usr/src/uts/common/io/comstar/port/qlt/qlt_regs.h
  usr/src/uts/common/io/fibre-channel/fca/qlc/Makefile
  usr/src/uts/common/io/fibre-channel/fca/qlc/ql_api.c
  usr/src/uts/common/io/fibre-channel/fca/qlc/ql_debug.c
  usr/src/uts/common/io/fibre-channel/fca/qlc/ql_fm.c
  usr/src/uts/common/io/fibre-channel/fca/qlc/ql_fw_2200.c
  usr/src/uts/common/io/fibre-channel/fca/qlc/ql_fw_2300.c
  usr/src/uts/common/io/fibre-channel/fca/qlc/ql_fw_2400.c
  usr/src/uts/common/io/fibre-channel/fca/qlc/ql_fw_2500.c
  usr/src/uts/common/io/fibre-channel/fca/qlc/ql_fw_2700.c
  usr/src/uts/common/io/fibre-channel/fca/qlc/ql_fw_6322.c
  usr/src/uts/common/io/fibre-channel/fca/qlc/ql_fw_8100.c
  usr/src/uts/common/io/fibre-channel/fca/qlc/ql_fw_8301fc.c
  usr/src/uts/common/io/fibre-channel/fca/qlc/ql_hba_fru.c
  usr/src/uts/common/io/fibre-channel/fca/qlc/ql_init.c
  usr/src/uts/common/io/fibre-channel/fca/qlc/ql_iocb.c
  usr/src/uts/common/io/fibre-channel/fca/qlc/ql_ioctl.c
  usr/src/uts/common/io/fibre-channel/fca/qlc/ql_isr.c
  usr/src/uts/common/io/fibre-channel/fca/qlc/ql_mbx.c
  usr/src/uts/common/io/fibre-channel/fca/qlc/ql_nx.c
  usr/src/uts/common/io/fibre-channel/fca/qlc/ql_xioctl.c
  usr/src/uts/common/io/fibre-channel/fca/qlc/qlc.conf
  usr/src/uts/common/sys/fibre-channel/fca/qlc/exioct.h
  usr/src/uts/common/sys/fibre-channel/fca/qlc/exioctso.h
  usr/src/uts/common/sys/fibre-channel/fca/qlc/ql_api.h
  usr/src/uts/common/sys/fibre-channel/fca/qlc/ql_apps.h
  usr/src/uts/common/sys/fibre-channel/fca/qlc/ql_debug.h
  usr/src/uts/common/sys/fibre-channel/fca/qlc/ql_fm.h
  usr/src/uts/common/sys/fibre-channel/fca/qlc/ql_init.h
  usr/src/uts/common/sys/fibre-channel/fca/qlc/ql_iocb.h
  usr/src/uts/common/sys/fibre-channel/fca/qlc/ql_ioctl.h
  usr/src/uts/common/sys/fibre-channel/fca/qlc/ql_isr.h
  usr/src/uts/common/sys/fibre-channel/fca/qlc/ql_mbx.h
  usr/src/uts/common/sys/fibre-channel/fca/qlc/ql_nx.h
  usr/src/uts/common/sys/fibre-channel/fca/qlc/ql_open.h
  usr/src/uts/common/sys/fibre-channel/fca/qlc/ql_xioctl.h
  usr/src/uts/intel/Makefile.intel
  usr/src/uts/intel/qlc_fw_2700/Makefile
  usr/src/uts/intel/qlc_fw_8301fc/Makefile
  usr/src/uts/sparc/Makefile.sparc
  usr/src/uts/sparc/qlc_fw_2700/Makefile
  usr/src/uts/sparc/qlc_fw_8301fc/Makefile
Labels: backport-PR

#308 7075 ahci: NULL pointer dereference in ahci_add_doneq() (r151028)
  usr/src/uts/common/io/sata/adapters/ahci/ahci.c
Labels: backport-PR

#309 Upstream merge upstream_merge/2018110101
  usr/src/cmd/format/menu_command.c
  usr/src/cmd/mdb/common/mdb/mdb_cmds.c
  usr/src/cmd/mdb/common/mdb/mdb_help.c
  usr/src/cmd/mdb/common/mdb/mdb_help.h
  usr/src/lib/libefi/common/rdwr_efi.c
  usr/src/uts/common/font/font.c
  usr/src/uts/common/io/tem.c
  usr/src/uts/common/krtld/bootrd.c
  usr/src/uts/common/krtld/kobj.c
  usr/src/uts/common/krtld/kobj_subr.c
  usr/src/uts/common/sys/efi_partition.h
  usr/src/uts/common/sys/kobj_impl.h
  usr/src/uts/common/sys/vtoc.h
  usr/src/uts/i86pc/os/fakebop.c
  usr/src/uts/intel/sys/bootconf.h
  usr/src/uts/sparc/os/bootops.c
  usr/src/uts/sun/sys/bootconf.h
Labels: upstream-merge

#318 9941 Noise from cfgadm plugins
  usr/src/lib/cfgadm_plugins/ib/common/cfga_ib.c
  usr/src/lib/cfgadm_plugins/sata/common/cfga_sata.c
  usr/src/lib/cfgadm_plugins/usb/common/cfga_usb.c
Labels: backport-PR

#317 Upstream merge/2018110801
  usr/src/Makefile.master
  usr/src/boot/sys/boot/efi/libefi/delay.c
  usr/src/boot/sys/boot/i386/libi386/biosdisk.c
  usr/src/boot/sys/boot/i386/loader/main.c
  usr/src/lib/cfgadm_plugins/ib/common/cfga_ib.c
  usr/src/lib/cfgadm_plugins/sata/common/cfga_sata.c
  usr/src/lib/cfgadm_plugins/usb/common/cfga_usb.c
  usr/src/uts/Makefile.uts
  usr/src/uts/common/io/hook.c
  usr/src/uts/intel/asm/cpu.h
Labels: backport-todo, upstream-merge

#324 Upstream merge/2018111501
  usr/src/boot/lib/libstand/ip.c
  usr/src/boot/lib/libstand/net.c
  usr/src/boot/lib/libstand/udp.c
  usr/src/boot/sys/boot/common/console.c
  usr/src/boot/sys/boot/common/disk.c
  usr/src/boot/sys/boot/common/part.c
  usr/src/boot/sys/boot/efi/libefi/efi_console.c
  usr/src/boot/sys/boot/efi/loader/Makefile.com
  usr/src/boot/sys/boot/efi/loader/arch/amd64/Makefile.inc
  usr/src/boot/sys/boot/efi/loader/arch/i386/Makefile.inc
  usr/src/boot/sys/boot/efi/loader/comconsole.c
  usr/src/boot/sys/boot/efi/loader/loader_efi.h
  usr/src/boot/sys/boot/efi/loader/main.c
  usr/src/boot/sys/boot/i386/gptzfsboot/Makefile
  usr/src/boot/sys/boot/i386/libi386/Makefile
  usr/src/boot/sys/boot/i386/libi386/biosdisk.c
  usr/src/boot/sys/boot/i386/libi386/bootinfo64.c
  usr/src/boot/sys/boot/i386/libi386/comconsole.c
  usr/src/boot/sys/boot/i386/libi386/cpuid.c
  usr/src/boot/sys/boot/i386/libi386/libi386.h
  usr/src/boot/sys/boot/i386/loader/main.c
  usr/src/boot/sys/boot/zfs/zfs.c
  usr/src/cmd/cmd-inet/usr.sbin/snoop/snoop.h
  usr/src/cmd/cmd-inet/usr.sbin/snoop/snoop_rport.c
  usr/src/cmd/cmd-inet/usr.sbin/snoop/snoop_slp.c
  usr/src/cmd/cmd-inet/usr.sbin/snoop/snoop_tftp.c
  usr/src/cmd/sgs/elfedit/common/elfedit_machelf.c
  usr/src/cmd/svc/common/manifest_hash.c
  usr/src/cmd/svc/svccfg/svccfg_libscf.c
  usr/src/pkg/manifests/system-header.mf
  usr/src/test/crypto-tests/tests/common/cryptotest_pkcs.c
  usr/src/tools/Makefile
  usr/src/uts/common/fs/zfs/sys/dmu.h
  usr/src/uts/common/inet/ip/rts.c
  usr/src/uts/common/io/cxgbe/t4nex/adapter.h
  usr/src/uts/common/io/cxgbe/t4nex/t4_l2t.c
  usr/src/uts/common/io/cxgbe/t4nex/t4_nexus.c
  usr/src/uts/common/io/ib/clients/rdsv3/ib_recv.c
  usr/src/uts/common/io/ib/clients/rdsv3/loop.c
  usr/src/uts/common/io/ib/clients/rdsv3/message.c
  usr/src/uts/common/io/ib/clients/rdsv3/rdma.c
  usr/src/uts/common/io/ib/clients/rdsv3/threads.c
  usr/src/uts/common/io/mac/mac_soft_ring.c
  usr/src/uts/common/io/qede/579xx/drivers/ecore/bcm_osal.h
  usr/src/uts/common/io/vioblk/vioblk.c
  usr/src/uts/common/io/vioif/vioif.c
  usr/src/uts/common/sys/Makefile
  usr/src/uts/common/sys/containerof.h
  usr/src/uts/common/sys/mac.h
  usr/src/uts/common/sys/mac_soft_ring.h
  usr/src/uts/common/sys/stddef.h
Labels: upstream-merge

#325 Ship sys/hma.h header (r151028)
  usr/src/pkg/manifests/system-header.mf
  usr/src/uts/i86pc/sys/Makefile
Labels: backport-PR

#330 Upstream merge/2018112201
  usr/src/boot/sys/boot/efi/boot1/Makefile.com
  usr/src/boot/sys/boot/i386/libi386/pxe.c
  usr/src/cmd/mdb/intel/kmdb/kctl/kctl_isadep.c
  usr/src/man/man1m/eeprom.1m
  usr/src/uts/common/io/consconfig_dacf.c
  usr/src/uts/common/os/space.c
  usr/src/uts/common/os/zone.c
  usr/src/uts/common/sys/consconfig_dacf.h
  usr/src/uts/common/sys/consdev.h
  usr/src/uts/common/sys/consplat.h
  usr/src/uts/common/sys/cpu_uarray.h
  usr/src/uts/common/sys/zone.h
  usr/src/uts/i86pc/boot/boot_console.c
  usr/src/uts/i86pc/dboot/dboot_startkern.c
  usr/src/uts/i86pc/io/consplat.c
Labels: upstream-merge

#333 Joyent merge/2018112801
  README.OmniOS
  usr/src/cmd/bhyve/uart_emul.c
Labels: backport-todo, upstream-merge
