Repository omniosorg/illumos-omnios, pull requests merged in 2018-09, with the labels that each got.

#263 9194 mechanism to override ashift at pool creation time
  usr/src/uts/common/fs/zfs/vdev.c
Labels: review

#267 dtrace requires cpp(1) for -C option
  usr/src/pkg/manifests/developer-dtrace.mf
Labels: review

#269 Joyent merge/2018091401
  README.OmniOS
  usr/src/cmd/bhyve/block_if.c
  usr/src/cmd/bhyve/block_if.h
  usr/src/cmd/bhyve/pci_virtio_block.c
  usr/src/cmd/bhyve/pci_virtio_viona.c
  usr/src/cmd/bhyve/uart_emul.c
  usr/src/compat/freebsd/sys/mutex.h
  usr/src/uts/common/disp/thread.c
  usr/src/uts/i86pc/io/vmm/intel/vmx.c
  usr/src/uts/i86pc/io/vmm/intel/vmx.h
  usr/src/uts/i86pc/io/vmm/vmm_sol_glue.c
Labels: backport-todo, review, upstream-merge

#272 Dashrev reversal
  usr/src/pkg/Makefile
Labels: review

#271 L1TF: OS-7222 thread_create() should ensure ->t_cpu is set (r151026)
  usr/src/uts/common/disp/thread.c
Labels: backport-PR, review

#270 L1TF: OS-7222 thread_create() should ensure ->t_cpu is set (r151022)
  usr/src/uts/common/disp/thread.c
Labels: backport-PR, review

#274 8450 UCODE_MAX_SIZE is too small for modern microcode
  usr/src/uts/common/sys/ucode.h
Labels: backport-PR, review

#277 Joyent merge/2018092701
  README.OmniOS
  usr/src/uts/i86pc/io/viona/viona.c
Labels: review, upstream-merge
