Repository omniosorg/illumos-omnios, pull requests merged in 2018-03, with the labels that each got.

#160 Upstream merge/2018030101
  exception_lists/check_rtime
  usr/src/boot/Makefile.version
  usr/src/boot/sys/boot/common/disk.c
  usr/src/boot/sys/boot/forth/support.4th
  usr/src/boot/sys/boot/i386/gptzfsboot/zfsboot.c
  usr/src/boot/sys/boot/zfs/zfs.c
  usr/src/cmd/cmd-crypto/tpmadm/main.c
  usr/src/common/crypto/ecc/ec2_163.c
  usr/src/common/crypto/ecc/ec2_193.c
  usr/src/common/crypto/ecc/ec2_233.c
  usr/src/common/crypto/ecc/ecl_gf.c
  usr/src/common/crypto/ecc/ecp_192.c
  usr/src/common/crypto/ecc/ecp_224.c
  usr/src/common/crypto/ecc/ecp_256.c
  usr/src/lib/cfgadm_plugins/pci/common/cfga.c
  usr/src/lib/cfgadm_plugins/sbd/common/ap_seq.c
  usr/src/lib/cfgadm_plugins/shp/common/shp.c
  usr/src/lib/libcurses/screen/scr_reset.c
  usr/src/lib/libdhcputil/common/dhcp_inittab.c
  usr/src/lib/libeti/form/common/regex.c
  usr/src/lib/libldap5/sources/ldap/ber/io.c
  usr/src/lib/libldap5/sources/ldap/common/friendly.c
  usr/src/lib/libldap5/sources/ldap/common/getdn.c
  usr/src/lib/libldap5/sources/ldap/common/ldaputf8.c
  usr/src/lib/libtecla/common/expand.c
  usr/src/lib/libtecla/common/getline.c
  usr/src/lib/libtecla/common/history.c
  usr/src/lib/pkcs11/libpkcs11/common/metaAttrManager.c
  usr/src/lib/sun_sas/common/devtree_device_disco.c
  usr/src/lib/sun_sas/common/sun_sas.c
  usr/src/tools/quick/make-smbsrv
  usr/src/tools/quick/make-zfs
  usr/src/uts/common/fs/zfs/vdev.c
Labels: upstream-merge

#167 Upstream merge joyent_merge/2018030601
  README.OmniOS
  usr/src/cmd/bhyve/Makefile.com
  usr/src/cmd/bhyve/bhyverun.c
  usr/src/cmd/bhyve/pci_passthru.c
  usr/src/cmd/bhyve/smbiostbl.c
  usr/src/cmd/bhyve/smbiostbl.h
  usr/src/cmd/devfsadm/i386/misc_link_i386.c
  usr/src/compat/freebsd/amd64/machine/cpu.h
  usr/src/compat/freebsd/contrib/dev/acpica/include/acpi.h
  usr/src/compat/freebsd/dev/pci/pcivar.h
  usr/src/compat/freebsd/sys/bus.h
  usr/src/compat/freebsd/sys/types.h
  usr/src/lib/libvmmapi/common/mapfile-vers
  usr/src/lib/libvmmapi/common/vmmapi.c
  usr/src/lib/libvmmapi/common/vmmapi.h
  usr/src/pkg/manifests/system-bhyve.mf
  usr/src/uts/common/fs/dev/sdev_plugin.c
  usr/src/uts/i86pc/Makefile.files
  usr/src/uts/i86pc/Makefile.i86pc
  usr/src/uts/i86pc/io/vmm/intel/vtd.c
  usr/src/uts/i86pc/io/vmm/io/iommu.c
  usr/src/uts/i86pc/io/vmm/io/ppt.c
  usr/src/uts/i86pc/io/vmm/io/ppt.conf
  usr/src/uts/i86pc/io/vmm/io/ppt.h
  usr/src/uts/i86pc/io/vmm/io/ppt_sol_glue.c
  usr/src/uts/i86pc/io/vmm/io/sol_iommu.c
  usr/src/uts/i86pc/io/vmm/io/sol_ppt.c
  usr/src/uts/i86pc/io/vmm/vmm_sol_dev.c
  usr/src/uts/i86pc/io/vmm/vmm_sol_glue.c
  usr/src/uts/i86pc/io/vmm/vmm_zsd.c
  usr/src/uts/i86pc/ppt/Makefile
  usr/src/uts/i86pc/sys/vmm_dev.h
  usr/src/uts/i86pc/sys/vmm_impl.h
  usr/src/uts/i86pc/vmm/Makefile
  usr/src/uts/intel/ia32/ml/modstubs.s
Labels: upstream-merge

#170 Upstream merge/2018030701
  usr/src/cmd/lp/lib/filters/loadfilters.c
  usr/src/cmd/uname/uname.c
  usr/src/lib/krb5/plugins/kdb/db2/adb_openclose.c
  usr/src/lib/krb5/plugins/kdb/db2/kdb_db2.c
  usr/src/lib/krb5/plugins/kdb/db2/libdb2/hash/hash_func.c
  usr/src/lib/krb5/ss/help.c
  usr/src/lib/krb5/ss/pager.c
  usr/src/lib/krb5/ss/ss_internal.h
  usr/src/lib/libnisdb/ldap_val.c
  usr/src/lib/libnisdb/nis_parse_ldap_util.c
  usr/src/lib/libnisdb/nis_parse_ldap_yp_util.c
  usr/src/lib/libnisdb/yptol/dit_access.c
  usr/src/lib/libpp/Makefile.com
  usr/src/lib/libpp/common/ppcontrol.c
  usr/src/lib/libshell/common/bltins/hist.c
  usr/src/lib/libshell/common/bltins/print.c
  usr/src/lib/libshell/common/bltins/test.c
  usr/src/lib/libshell/common/bltins/typeset.c
  usr/src/lib/libshell/common/edit/emacs.c
  usr/src/lib/libshell/common/edit/hexpand.c
  usr/src/lib/libshell/common/edit/vi.c
  usr/src/lib/libshell/common/sh/args.c
  usr/src/lib/libshell/common/sh/lex.c
  usr/src/lib/libshell/common/sh/macro.c
  usr/src/lib/libshell/common/sh/name.c
  usr/src/lib/libshell/common/sh/parse.c
  usr/src/lib/libshell/common/sh/path.c
  usr/src/lib/libshell/common/sh/streval.c
  usr/src/lib/libshell/common/sh/xec.c
  usr/src/lib/libsldap/common/ns_config.c
  usr/src/lib/libsldap/common/ns_standalone.c
  usr/src/lib/libsmbfs/smb/rap.c
  usr/src/lib/libsmbfs/smb/ssnsetup.c
  usr/src/lib/smbsrv/libsmb/common/smb_domain.c
  usr/src/man/man1/uname.1
  usr/src/man/man1m/mount_smbfs.1m
  usr/src/uts/common/fs/fs_subr.c
  usr/src/uts/common/fs/fs_subr.h
  usr/src/uts/common/fs/lookup.c
  usr/src/uts/common/fs/smbclnt/smbfs/smbfs_smb.c
  usr/src/uts/common/fs/smbclnt/smbfs/smbfs_subr.h
  usr/src/uts/common/fs/smbclnt/smbfs/smbfs_subr2.c
  usr/src/uts/common/fs/smbclnt/smbfs/smbfs_vfsops.c
  usr/src/uts/common/fs/smbclnt/smbfs/smbfs_vnops.c
  usr/src/uts/common/fs/ufs/ufs_vnops.c
  usr/src/uts/common/io/audio/drv/audioemu10k/audioemu10k.c
  usr/src/uts/common/io/devpoll.c
  usr/src/uts/common/io/dls/dls_mgmt.c
  usr/src/uts/common/os/fio.c
  usr/src/uts/common/os/zone.c
  usr/src/uts/common/sys/file.h
  usr/src/uts/common/sys/poll_impl.h
  usr/src/uts/common/sys/user.h
  usr/src/uts/i86pc/ppt/Makefile
  usr/src/uts/i86pc/vmm/Makefile
Labels: pending-upstream, upstream-merge

#171 Upstream merge joyent_merge/2018030801
  README.OmniOS
  usr/src/cmd/Makefile
  usr/src/cmd/bhhwcompat/Makefile
  usr/src/cmd/bhhwcompat/bhhwcompat.c
  usr/src/cmd/bhyve/Makefile.com
  usr/src/cmd/bhyve/pci_passthru.c
  usr/src/cmd/bhyvectl/bhyvectl.c
  usr/src/cmd/devfsadm/i386/misc_link_i386.c
  usr/src/compat/freebsd/dev/pci/pcivar.h
  usr/src/lib/libvmmapi/common/vmmapi.c
  usr/src/lib/libvmmapi/common/vmmapi.h
  usr/src/pkg/manifests/system-bhyve.mf
  usr/src/uts/i86pc/Makefile.files
  usr/src/uts/i86pc/io/vmm/intel/vmx.c
  usr/src/uts/i86pc/io/vmm/io/ppt.c
  usr/src/uts/i86pc/io/vmm/io/ppt.h
  usr/src/uts/i86pc/io/vmm/io/ppt_sol_glue.c
  usr/src/uts/i86pc/io/vmm/vmm.c
  usr/src/uts/i86pc/io/vmm/vmm_sol_dev.c
  usr/src/uts/i86pc/ppt/Makefile
  usr/src/uts/i86pc/sys/ppt_dev.h
  usr/src/uts/i86pc/sys/vmm.h
  usr/src/uts/i86pc/sys/vmm_dev.h
  usr/src/uts/intel/ia32/ml/modstubs.s
Labels: upstream-merge

#172 5709 Add binary compatibility with Solaris 10 update 10.
  usr/src/lib/libc/port/mapfile-vers
Labels: enhancement

#176 Remove openssl dependency from libipsecutil
  usr/src/lib/Makefile
  usr/src/lib/libipsecutil/Makefile.com
  usr/src/lib/libipsecutil/common/ipsec_libssl_setup.c
  usr/src/lib/libipsecutil/common/ipsec_util.c
  usr/src/lib/libipsecutil/common/ipsec_util.h
  usr/src/lib/libkmf/include/kmfapi.h
  usr/src/lib/libkmf/libkmf/Makefile.com
  usr/src/lib/libkmf/libkmf/common/mapfile-vers
  usr/src/lib/libkmf/libkmf/common/rdn_parser.c
Labels: enhancement, upstream-candidate

#179 Upstream merge upstream_merge/2018032201
  usr/src/cmd/mdb/common/modules/zfs/zfs.c
  usr/src/cmd/stat/arcstat/arcstat.pl
  usr/src/cmd/zdb/zdb.c
  usr/src/cmd/zpool/zpool_main.c
  usr/src/cmd/ztest/ztest.c
  usr/src/common/zfs/zfs_comutil.c
  usr/src/common/zfs/zfs_comutil.h
  usr/src/lib/libzfs/common/libzfs.h
  usr/src/lib/libzfs/common/libzfs_import.c
  usr/src/lib/libzfs/common/libzfs_pool.c
  usr/src/lib/libzpool/common/llib-lzpool
  usr/src/lib/scsi/plugins/ses/ses2/common/ses2_element.c
  usr/src/test/zfs-tests/include/commands.cfg
  usr/src/test/zfs-tests/tests/functional/cli_root/zpool_import/zpool_import.kshlib
  usr/src/test/zfs-tests/tests/functional/removal/removal_with_ganging.ksh
  usr/src/test/zfs-tests/tests/perf/regression/random_reads.ksh
  usr/src/test/zfs-tests/tests/perf/regression/random_readwrite.ksh
  usr/src/test/zfs-tests/tests/perf/regression/random_writes.ksh
  usr/src/test/zfs-tests/tests/perf/regression/sequential_reads.ksh
  usr/src/test/zfs-tests/tests/perf/regression/sequential_writes.ksh
  usr/src/uts/common/fs/smbclnt/smbfs/smbfs.h
  usr/src/uts/common/fs/smbclnt/smbfs/smbfs_client.c
  usr/src/uts/common/fs/smbclnt/smbfs/smbfs_node.c
  usr/src/uts/common/fs/smbclnt/smbfs/smbfs_node.h
  usr/src/uts/common/fs/smbclnt/smbfs/smbfs_subr.h
  usr/src/uts/common/fs/smbclnt/smbfs/smbfs_subr2.c
  usr/src/uts/common/fs/smbclnt/smbfs/smbfs_vfsops.c
  usr/src/uts/common/fs/smbclnt/smbfs/smbfs_vnops.c
  usr/src/uts/common/fs/zfs/arc.c
  usr/src/uts/common/fs/zfs/dbuf.c
  usr/src/uts/common/fs/zfs/metaslab.c
  usr/src/uts/common/fs/zfs/spa.c
  usr/src/uts/common/fs/zfs/sys/zthr.h
  usr/src/uts/common/fs/zfs/vdev.c
  usr/src/uts/common/fs/zfs/vdev_label.c
  usr/src/uts/common/fs/zfs/zthr.c
  usr/src/uts/common/sys/fs/zfs.h
Labels: upstream-merge

#180 9317 FMD crashes with zero-length allocation (r151024)
  README.OmniOS
  usr/src/lib/scsi/plugins/ses/ses2/common/ses2_element.c
Labels: backport-PR, bug

#182 Upstream merge joyent_merge/2018032201
  README.OmniOS
  exception_lists/check_rtime
  usr/src/cmd/bhhwcompat/bhhwcompat.c
  usr/src/cmd/bhyve/Makefile
  usr/src/cmd/bhyve/Makefile.com
  usr/src/cmd/bhyve/amd64/Makefile
  usr/src/cmd/bhyve/pci_lpc.c
  usr/src/cmd/bhyvectl/Makefile
  usr/src/cmd/bhyvectl/Makefile.com
  usr/src/cmd/bhyvectl/amd64/Makefile
  usr/src/cmd/devfsadm/i386/misc_link_i386.c
  usr/src/pkg/manifests/system-bhyve.mf
  usr/src/tools/scripts/nightly.sh
  usr/src/uts/common/fs/dev/sdev_plugin.c
  usr/src/uts/common/fs/dev/sdev_vnops.c
  usr/src/uts/i86pc/io/vmm/amd/svm_support.s
  usr/src/uts/i86pc/io/vmm/io/ppt.c
  usr/src/uts/i86pc/io/vmm/vmm_sol_dev.c
  usr/src/uts/i86pc/sys/vmm.h
Labels: upstream-merge

#181 9317 FMD crashes with zero-length allocation (r151022)
  README.OmniOS
  usr/src/lib/scsi/plugins/ses/ses2/common/ses2_element.c
Labels: backport-PR, bug

#183 Upstream merge/2018032801
  usr/src/boot/sys/boot/common/multiboot.S
  usr/src/boot/sys/boot/efi/boot1/Makefile
  usr/src/boot/sys/boot/efi/boot1/boot1.c
  usr/src/boot/sys/boot/i386/gptzfsboot/Makefile
  usr/src/boot/sys/boot/i386/gptzfsboot/zfsboot.c
  usr/src/boot/sys/boot/i386/libi386/multiboot.c
  usr/src/boot/sys/sys/multiboot.h
  usr/src/cmd/cmd-inet/sbin/dhcpagent/agent.c
  usr/src/cmd/cmd-inet/usr.bin/chat/chat.c
  usr/src/cmd/cmd-inet/usr.bin/ftp/cmds.c
  usr/src/cmd/cmd-inet/usr.bin/ftp/domacro.c
  usr/src/cmd/cmd-inet/usr.lib/ilbd/ilbd_rules.c
  usr/src/cmd/cmd-inet/usr.lib/in.mpathd/mpd_main.c
  usr/src/cmd/cmd-inet/usr.sbin/ifconfig/ifconfig.c
  usr/src/cmd/cmd-inet/usr.sbin/in.telnetd.c
  usr/src/cmd/cmd-inet/usr.sbin/inetadm/inetadm.c
  usr/src/cmd/cmd-inet/usr.sbin/ipqosconf/ipqosconf.c
  usr/src/cmd/cmd-inet/usr.sbin/ipsecutils/ikeadm.c
  usr/src/cmd/cmd-inet/usr.sbin/snoop/snoop_nis.c
  usr/src/cmd/fs.d/autofs/autod_nfs.c
  usr/src/cmd/fs.d/ff.c
  usr/src/cmd/fs.d/hsfs/labelit/labelit.c
  usr/src/cmd/fs.d/smbclnt/smbutil/smbutil.c
  usr/src/cmd/fs.d/udfs/fsck/pass1.c
  usr/src/cmd/fs.d/ufs/fsdb/fsdb.c
  usr/src/cmd/fs.d/ufs/mkfs/mkfs.c
  usr/src/cmd/fs.d/ufs/mount/mount.c
  usr/src/cmd/fs.d/ufs/newfs/newfs.c
  usr/src/cmd/ldap/common/common.c
  usr/src/cmd/ldap/common/ldapsearch.c
  usr/src/cmd/ldap/ns_ldap/ldapaddent.c
  usr/src/cmd/ldap/ns_ldap/ldapclient.c
  usr/src/cmd/mdb/common/modules/ip/ip.c
  usr/src/cmd/smbsrv/smbstat/smbstat.c
  usr/src/uts/i86pc/io/immu.c
  usr/src/uts/i86pc/io/immu_dmar.c
Labels: upstream-merge

#184 Joyent merge/2018032801
  README.OmniOS
  exception_lists/check_rtime
  usr/contrib/freebsd/sys/queue.h
  usr/src/cmd/bhyve/Makefile
  usr/src/cmd/bhyve/bhyverun.c
  usr/src/cmd/bhyve/mevent.c
  usr/src/cmd/bhyve/mevent_test.c
  usr/src/cmd/bhyve/test/Makefile
  usr/src/cmd/bhyve/test/Makefile.com
  usr/src/cmd/bhyve/test/Makefile.subdirs
  usr/src/cmd/bhyve/test/Makefile.targ
  usr/src/cmd/bhyve/test/scripts/Makefile
  usr/src/cmd/bhyve/test/scripts/bhyvetest.ksh
  usr/src/cmd/bhyve/test/tst/Makefile
  usr/src/cmd/bhyve/test/tst/mevent/Makefile
  usr/src/cmd/bhyve/test/tst/mevent/lists.delete.c
  usr/src/cmd/bhyve/test/tst/mevent/mevent.c
  usr/src/cmd/bhyve/test/tst/mevent/read.disable.c
  usr/src/cmd/bhyve/test/tst/mevent/read.pause.c
  usr/src/cmd/bhyve/test/tst/mevent/read.requeue.c
  usr/src/cmd/bhyve/test/tst/mevent/testlib.c
  usr/src/cmd/bhyve/test/tst/mevent/testlib.h
  usr/src/cmd/bhyve/uart_emul.c
  usr/src/pkg/manifests/system-bhyve-tests.mf
  usr/src/uts/i86pc/io/viona/viona.c
Labels: upstream-merge
