Repository omniosorg/illumos-omnios, pull requests merged in 2018-08, with the labels that each got.

#251 Backports r26
  usr/src/cmd/mdb/i86pc/modules/unix/unix.c
  usr/src/cmd/mdb/i86pc/modules/unix/unix_sup.h
  usr/src/cmd/mdb/i86pc/modules/unix/unix_sup.s
  usr/src/pkg/manifests/system-test-ostest.mf
  usr/src/test/os-tests/runfiles/default.run
  usr/src/test/os-tests/tests/i386/Makefile
  usr/src/test/os-tests/tests/i386/badseg.c
  usr/src/uts/i86pc/io/vmm/intel/vmx.c
  usr/src/uts/i86pc/io/vmm/vmm.c
  usr/src/uts/i86pc/ml/kpti_trampolines.s
  usr/src/uts/i86pc/ml/locore.s
  usr/src/uts/intel/ia32/os/desctbls.c
  usr/src/uts/intel/sys/x86_archext.h
Labels: backport-PR

#250 Backports r22
  usr/src/cmd/mdb/i86pc/modules/unix/unix.c
  usr/src/cmd/mdb/i86pc/modules/unix/unix_sup.h
  usr/src/cmd/mdb/i86pc/modules/unix/unix_sup.s
  usr/src/test/os-tests/runfiles/default.run
  usr/src/test/os-tests/tests/i386/Makefile
  usr/src/test/os-tests/tests/i386/badseg.c
  usr/src/uts/i86pc/ml/kpti_trampolines.s
  usr/src/uts/i86pc/ml/locore.s
  usr/src/uts/intel/ia32/os/desctbls.c
  usr/src/uts/intel/sys/x86_archext.h
Labels: backport-PR

#255 Upstream merge/2018082201
  usr/src/boot/Makefile.version
  usr/src/boot/sys/boot/i386/gptzfsboot/zfsboot.c
  usr/src/boot/sys/boot/i386/libi386/biosdisk.c
  usr/src/boot/sys/boot/libstand/Makefile.com
  usr/src/cmd/boot/installgrub/installgrub.c
  usr/src/cmd/getent/Makefile
  usr/src/cmd/getent/dogetauthattr.c
  usr/src/cmd/getent/dogetexecattr.c
  usr/src/cmd/getent/dogetipnodes.c
  usr/src/cmd/getent/dogetprofattr.c
  usr/src/cmd/getent/dogetuserattr.c
  usr/src/cmd/getent/getent.c
  usr/src/cmd/getent/getent.h
  usr/src/cmd/mdb/common/kmdb/kaif_start.c
  usr/src/grub/grub-0.97/Makefile.solaris.defs
  usr/src/head/iso/stddef_iso.h
  usr/src/head/iso/stdlib_c11.h
  usr/src/head/iso/string_iso.h
  usr/src/head/stdint.h
  usr/src/lib/libc/amd64/Makefile
  usr/src/lib/libc/i386/Makefile.com
  usr/src/lib/libc/inc/libc.h
  usr/src/lib/libc/port/gen/memset_s.c
  usr/src/lib/libc/port/gen/set_constraint_handler_s.c
  usr/src/lib/libc/port/mapfile-vers
  usr/src/lib/libc/port/threads/assfail.c
  usr/src/lib/libc/sparc/Makefile.com
  usr/src/lib/libc/sparcv9/Makefile.com
  usr/src/lib/libpkg/common/tputcfent.c
  usr/src/man/man1m/getent.1m
  usr/src/man/man3c/Makefile
  usr/src/man/man3c/memset_s.3c
  usr/src/man/man3c/set_constraint_handler_s.3c
  usr/src/man/man3secdb/getauthattr.3secdb
  usr/src/man/man3secdb/getexecattr.3secdb
  usr/src/man/man3secdb/getprofattr.3secdb
  usr/src/man/man3secdb/getuserattr.3secdb
  usr/src/man/man3secdb/kva_match.3secdb
  usr/src/man/man3xnet/send.3xnet
  usr/src/man/man3xnet/sendmsg.3xnet
  usr/src/man/man3xnet/sendto.3xnet
  usr/src/pkg/manifests/system-library.man3c.inc
  usr/src/pkg/manifests/system-test-libctest.mf
  usr/src/test/libc-tests/runfiles/default.run
  usr/src/test/libc-tests/tests/Makefile
  usr/src/test/libc-tests/tests/memset_s.c
  usr/src/test/libc-tests/tests/set_constraint_handler_s.c
  usr/src/uts/common/io/iwn/if_iwn.c
  usr/src/uts/common/io/iwn/if_iwnvar.h
  usr/src/uts/common/io/scsi/targets/st.c
  usr/src/uts/common/sys/feature_tests.h
  usr/src/uts/i86pc/os/fakebop.c
  usr/src/uts/i86pc/os/mp_startup.c
  usr/src/uts/intel/amd64/sys/kdi_regs.h
  usr/src/uts/intel/kdi/kdi_asm.s
  usr/src/uts/intel/kdi/kdi_idt.c
Labels: upstream-merge

#257 Upstream merge joyent_merge/2018082301
  README.OmniOS
  exception_lists/packaging
  usr/src/cmd/mailx/Makefile
  usr/src/cmd/mailx/hdr/def.h
  usr/src/common/brand/lx/tools/Makefile
  usr/src/common/brand/lx/tools/gen_errno.c
  usr/src/lib/Makefile
  usr/src/lib/brand/lx/lx_init/Makefile
  usr/src/lib/brand/lx/lx_init/lxinit.c
  usr/src/lib/brand/lx/lx_init/run_command.c
  usr/src/lib/libcmdutils/Makefile.com
  usr/src/lib/libcmdutils/common/mapfile-vers
  usr/src/lib/libcmdutils/libcmdutils.h
  usr/src/lib/libcustr/Makefile
  usr/src/lib/libcustr/Makefile.com
  usr/src/lib/libcustr/amd64/Makefile
  usr/src/lib/libcustr/common/custr.c
  usr/src/lib/libcustr/common/libcustr.h
  usr/src/lib/libcustr/common/llib-lcustr
  usr/src/lib/libcustr/common/mapfile-vers
  usr/src/lib/libcustr/i386/Makefile
  usr/src/lib/libcustr/sparc/Makefile
  usr/src/lib/libcustr/sparcv9/Makefile
  usr/src/lib/libkmf/libkmf/Makefile.com
  usr/src/lib/libkmf/libkmf/common/rdn_parser.c
  usr/src/pkg/manifests/system-library.mf
  usr/src/test/libc-tests/tests/symbols/Makefile
  usr/src/test/libc-tests/tests/symbols/symbols_test.c
  usr/src/uts/common/os/main.c
  usr/src/uts/i86pc/Makefile.files
  usr/src/uts/i86pc/io/vmm/amd/svm.c
  usr/src/uts/i86pc/io/vmm/intel/vmx.c
  usr/src/uts/i86pc/io/vmm/intel/vmx.h
  usr/src/uts/i86pc/io/vmm/intel/vmx_support.s
  usr/src/uts/i86pc/io/vmm/vm/vm_object.h
  usr/src/uts/i86pc/io/vmm/vmm.c
  usr/src/uts/i86pc/io/vmm/vmm_sol_dev.c
  usr/src/uts/i86pc/io/vmm/vmm_sol_glue.c
  usr/src/uts/i86pc/io/vmm/vmm_sol_vm.c
  usr/src/uts/i86pc/ml/hma_asm.s
  usr/src/uts/i86pc/os/hma.c
  usr/src/uts/i86pc/os/mp_startup.c
  usr/src/uts/i86pc/os/pc_hvm.c
  usr/src/uts/i86pc/os/timestamp.c
  usr/src/uts/i86pc/sys/hma.h
  usr/src/uts/i86pc/sys/machsystm.h
  usr/src/uts/intel/sys/x86_archext.h
Labels: upstream-merge

#260 9769 SMB domain logon fails with I18N user name (r151026)
  README.OmniOS
  usr/src/cmd/smbsrv/dtrace/smbd-all.d
  usr/src/cmd/smbsrv/dtrace/smbd-authsvc.d
  usr/src/cmd/smbsrv/dtrace/smbd-doorsvc.d
  usr/src/cmd/smbsrv/dtrace/smbd-pipesvc.d
  usr/src/lib/libmlrpc/common/ndr_process.c
  usr/src/tools/quick/make-smbsrv
Labels: backport-PR

#259 Upstream merge upstream_merge/2018082901
  usr/src/Makefile.master
  usr/src/boot/sys/boot/common/multiboot2.c
  usr/src/boot/sys/boot/efi/boot1/Makefile
  usr/src/boot/sys/boot/efi/libefi/Makefile
  usr/src/boot/sys/boot/efi/loader/Makefile
  usr/src/boot/sys/boot/efi/loader/memmap.c
  usr/src/boot/sys/boot/ficl/Makefile.inc
  usr/src/boot/sys/boot/i386/btx/btx/Makefile
  usr/src/boot/sys/boot/i386/btx/btxldr/Makefile
  usr/src/boot/sys/boot/i386/btx/lib/Makefile
  usr/src/boot/sys/boot/i386/cdboot/Makefile
  usr/src/boot/sys/boot/i386/gptzfsboot/Makefile
  usr/src/boot/sys/boot/i386/libi386/Makefile
  usr/src/boot/sys/boot/i386/libi386/biosdisk.c
  usr/src/boot/sys/boot/i386/libi386/linux.c
  usr/src/boot/sys/boot/i386/loader/Makefile
  usr/src/boot/sys/boot/i386/pxeldr/Makefile
  usr/src/boot/sys/boot/libstand/Makefile.com
  usr/src/boot/sys/boot/zfs/Makefile.com
  usr/src/cmd/format/menu_command.c
  usr/src/cmd/mailx/Makefile
  usr/src/cmd/smbsrv/dtrace/smbd-all.d
  usr/src/cmd/smbsrv/dtrace/smbd-authsvc.d
  usr/src/cmd/smbsrv/dtrace/smbd-doorsvc.d
  usr/src/cmd/smbsrv/dtrace/smbd-pipesvc.d
  usr/src/cmd/svr4pkg/hdrs/libinst.h
  usr/src/cmd/svr4pkg/hdrs/messages.h
  usr/src/cmd/svr4pkg/pkgadd/main.c
  usr/src/grub/grub-0.97/Makefile.solaris.defs
  usr/src/head/errno.h
  usr/src/head/iso/stddef_iso.h
  usr/src/lib/libc/port/gen/memset_s.c
  usr/src/lib/libc/port/gen/set_constraint_handler_s.c
  usr/src/lib/libcustr/common/custr.c
  usr/src/lib/libcustr/common/llib-lcustr
  usr/src/lib/libmlrpc/common/ndr_process.c
  usr/src/man/man1m/zfs.1m
  usr/src/man/man3c/Makefile
  usr/src/man/man3c/getopt.3c
  usr/src/man/man3c/getopt_long.3c
  usr/src/pkg/manifests/system-library.man3c.inc
  usr/src/psm/stand/bootblks/ufs/i386/Makefile
  usr/src/test/libc-tests/tests/memset_s.c
  usr/src/test/os-tests/tests/i386/badseg.c
  usr/src/tools/cw/Makefile
  usr/src/tools/cw/cw.1onbld
  usr/src/tools/cw/cw.c
  usr/src/tools/env/omnios-illumos-gate.sh
  usr/src/tools/env/omnios-illumos-omnios.sh
  usr/src/tools/quick/make-smbsrv
  usr/src/tools/scripts/bldenv.sh
  usr/src/tools/scripts/nightly.sh
  usr/src/tools/scripts/ws.sh
  usr/src/uts/common/fs/smbsrv/smb_cmn_rename.c
  usr/src/uts/common/sys/feature_tests.h
Labels: backport-todo, upstream-merge

#261 Upstream merge upstream_merge/2018082901
  README.OmniOS
  usr/src/pkg/manifests/system-header.mf
  usr/src/uts/common/brand/lx/os/lx_audit.c
  usr/src/uts/common/io/sata/adapters/ahci/ahci.c
  usr/src/uts/common/rpc/rpcmod.c
  usr/src/uts/common/rpc/sec_gss/svc_rpcsec_gss.c
  usr/src/uts/common/rpc/svc.c
  usr/src/uts/common/rpc/svc.h
  usr/src/uts/common/rpc/svc_clts.c
  usr/src/uts/common/rpc/svc_cots.c
  usr/src/uts/common/rpc/svc_rdma.c
  usr/src/uts/i86pc/io/apix/apix_utils.c
  usr/src/uts/i86pc/io/pcplusmp/apic.c
  usr/src/uts/i86pc/os/ht.c
  usr/src/uts/i86pc/sys/ht.h
  usr/src/uts/sun4/sys/ht.h
Labels: backport-todo, upstream-merge
