Repository omniosorg/illumos-omnios, pull requests merged in 2018-02, with the labels that each got.

#150 Upstream merge joyent_merge/2018021501
  README.OmniOS
Labels: upstream-merge

#152 8984 fix for 6764 breaks ACL inheritance (r151022)
  usr/src/uts/common/fs/zfs/zfs_acl.c
Labels: backport-PR

#153 8984 fix for 6764 breaks ACL inheritance (r151024)
  usr/src/uts/common/fs/zfs/zfs_acl.c
Labels: backport-PR

#154 Upstream merge joyent_merge/2018022101
  README.OmniOS
  usr/src/lib/brand/lx/lx_brand/common/clone.c
  usr/src/lib/brand/lx/lx_brand/common/signal.c
  usr/src/lib/brand/lx/lx_brand/common/stack.c
  usr/src/pkg/manifests/system-header.mf
  usr/src/uts/common/Makefile.files
  usr/src/uts/common/fs/dev/sdev_plugin.c
  usr/src/uts/common/fs/dev/sdev_subr.c
  usr/src/uts/common/fs/dev/sdev_vfsops.c
  usr/src/uts/common/io/pciex/pcie.c
  usr/src/uts/common/sys/Makefile
  usr/src/uts/common/sys/fs/sdev_impl.h
  usr/src/uts/common/sys/fs/sdev_plugin.h
  usr/src/uts/common/sys/pcie.h
  usr/src/uts/common/sys/pcie_impl.h
  usr/src/uts/common/vm/vm_page.c
  usr/src/uts/i86pc/Makefile.files
  usr/src/uts/i86pc/io/apix/apix.c
  usr/src/uts/i86pc/io/pcplusmp/apic.c
  usr/src/uts/i86pc/io/pcplusmp/apic_common.c
  usr/src/uts/i86pc/io/psm/uppc.c
  usr/src/uts/i86pc/os/mp_machdep.c
  usr/src/uts/i86pc/sys/apic_common.h
  usr/src/uts/i86pc/sys/psm_types.h
  usr/src/uts/i86pc/sys/smp_impldefs.h
  usr/src/uts/i86pc/vm/seg_vmm.c
  usr/src/uts/i86pc/vm/seg_vmm.h
  usr/src/uts/i86xpv/io/psm/xpv_psm.c
  usr/src/uts/i86xpv/io/psm/xpv_uppc.c
  usr/src/uts/intel/dev/Makefile
Labels: upstream-merge

#155 8680 Time of Day clock error (r151022)
  usr/src/uts/i86pc/io/todpc_subr.c
Labels: backport-PR

#156 8680 Time of Day clock error (r151024)
  usr/src/uts/i86pc/io/todpc_subr.c
Labels: backport-PR

#158 Integrate PMBR & OpenSSL 1.1 changes.
  exception_lists/copyright
  usr/src/Makefile
  usr/src/Makefile.master
  usr/src/cmd/cmd-crypto/tpmadm/main.c
  usr/src/cmd/fdisk/fdisk.c
  usr/src/cmd/sendmail/src/tls.c
  usr/src/data/hwdata/Makefile
  usr/src/data/hwdata/THIRDPARTYLICENSE.efifixes.descrip
  usr/src/data/hwdata/THIRDPARTYLICENSE.efifixes.tmpl
  usr/src/data/hwdata/efi.fixes
  usr/src/lib/krb5/plugins/preauth/pkinit/pkinit_crypto_openssl.c
  usr/src/lib/krb5/plugins/preauth/pkinit/pkinit_crypto_openssl.h
  usr/src/lib/libefi/Makefile.com
  usr/src/lib/libefi/common/rdwr_efi.c
  usr/src/lib/libipsecutil/common/ipsec_libssl_setup.c
  usr/src/lib/libkmf/plugins/kmf_openssl/Makefile.com
  usr/src/lib/libkmf/plugins/kmf_openssl/common/compat.c
  usr/src/lib/libkmf/plugins/kmf_openssl/common/compat.h
  usr/src/lib/libkmf/plugins/kmf_openssl/common/openssl_spi.c
  usr/src/lib/pkcs11/pkcs11_tpm/Makefile.com
  usr/src/lib/pkcs11/pkcs11_tpm/common/tpm_specific.c
  usr/src/lib/pkcs11/pkcs11_tpm/common/tpmtok_int.h
  usr/src/man/man1m/fdisk.1m
  usr/src/man/man3ext/efi_alloc_and_init.3ext
  usr/src/pkg/manifests/system-data-hardware-registry.mf
  usr/src/tools/scripts/nightly.sh
Labels: upstream-candidate
