Repository omniosorg/illumos-omnios, pull requests merged in 2018-04, with the labels that each got.

#187 Upstream merge joyent_merge/2018040501
  README.OmniOS
  usr/src/cmd/bhyve/pci_virtio_viona.c
  usr/src/cmd/mdb/common/modules/genunix/memory.c
  usr/src/cmd/mdb/i86pc/modules/apix/apix.c
  usr/src/cmd/mdb/i86pc/modules/common/intr_common.c
  usr/src/cmd/mdb/i86pc/modules/common/intr_common.h
  usr/src/cmd/mdb/i86pc/modules/pcplusmp/pcplusmp.c
  usr/src/cmd/mdb/intel/amd64/Makefile
  usr/src/cmd/mdb/intel/amd64/vmm/Makefile
  usr/src/cmd/mdb/intel/amd64/vmm/amd64/Makefile
  usr/src/cmd/mdb/intel/amd64/vmm/vmm.c
  usr/src/cmd/mdb/intel/mdb/mdb_amd64util.c
  usr/src/cmd/mdb/intel/mdb/mdb_kreg.h
  usr/src/compat/freebsd/amd64/machine/atomic.h
  usr/src/compat/freebsd/amd64/machine/smp.h
  usr/src/pkg/manifests/system-bhyve.mf
  usr/src/uts/common/sys/vnode.h
  usr/src/uts/common/vm/page_lock.c
  usr/src/uts/common/vm/page_retire.c
  usr/src/uts/common/vm/seg_kmem.c
  usr/src/uts/common/vm/seg_kmem.h
  usr/src/uts/i86pc/dboot/dboot_startkern.c
  usr/src/uts/i86pc/io/apix/apix.c
  usr/src/uts/i86pc/io/apix/apix_regops.c
  usr/src/uts/i86pc/io/pcplusmp/apic.c
  usr/src/uts/i86pc/io/pcplusmp/apic_common.c
  usr/src/uts/i86pc/io/psm/uppc.c
  usr/src/uts/i86pc/io/vmm/intel/vmx.c
  usr/src/uts/i86pc/io/vmm/intel/vmx_support.s
  usr/src/uts/i86pc/io/vmm/vm/vm_glue.h
  usr/src/uts/i86pc/io/vmm/vmm.c
  usr/src/uts/i86pc/io/vmm/vmm_sol_dev.c
  usr/src/uts/i86pc/io/vmm/vmm_sol_glue.c
  usr/src/uts/i86pc/io/vmm/vmm_sol_vm.c
  usr/src/uts/i86pc/ml/kpti_trampolines.s
  usr/src/uts/i86pc/ml/offsets.in
  usr/src/uts/i86pc/os/ddi_impl.c
  usr/src/uts/i86pc/os/mp_machdep.c
  usr/src/uts/i86pc/os/pc_hvm.c
  usr/src/uts/i86pc/os/startup.c
  usr/src/uts/i86pc/sys/apic.h
  usr/src/uts/i86pc/sys/apic_common.h
  usr/src/uts/i86pc/sys/machparam.h
  usr/src/uts/i86pc/sys/psm_types.h
  usr/src/uts/i86pc/sys/smp_impldefs.h
  usr/src/uts/i86pc/sys/vmm_dev.h
  usr/src/uts/i86pc/sys/vmm_impl.h
  usr/src/uts/i86pc/vm/seg_vmm.c
  usr/src/uts/i86xpv/io/psm/xpv_psm.c
  usr/src/uts/i86xpv/io/psm/xpv_uppc.c
  usr/src/uts/intel/amd64/sys/kdi_regs.h
  usr/src/uts/intel/kdi/kdi_asm.s
  usr/src/uts/sun4/os/startup.c
Labels: upstream-merge

#189 OS-4948 vioif should not log to the console on boot, or ever
  usr/src/uts/common/io/vioif/vioif.c
Labels: backport-todo

#190 OS-4948 vioif should not log to the console on boot, or ever (r151026)
  usr/src/uts/common/io/vioif/vioif.c
Labels: backport-PR

#192 Upstream merge/2018041101
  exception_lists/check_rtime
  exception_lists/manlint
  usr/src/Makefile.master
  usr/src/cmd/cmd-inet/usr.bin/netstat/netstat.c
  usr/src/cmd/fm/eversholt/eftinfo/common/eftinfo.c
  usr/src/cmd/fm/eversholt/esc/common/escmain.c
  usr/src/cmd/fm/modules/common/eversholt/eval.c
  usr/src/cmd/policykit/polkit-is-privileged.c
  usr/src/cmd/pools/poolstat/poolstat.c
  usr/src/cmd/refer/refer2.c
  usr/src/cmd/smbsrv/smbd/server.xml
  usr/src/cmd/tbl/t4.c
  usr/src/cmd/tbl/t6.c
  usr/src/cmd/tbl/t7.c
  usr/src/cmd/tbl/t8.c
  usr/src/cmd/tcpd/safe_finger.c
  usr/src/cmd/tr/tr.c
  usr/src/cmd/tsol/updatehome/updatehome.c
  usr/src/common/bzip2/decompress.c
  usr/src/lib/libmvec/common/__vcos.c
  usr/src/lib/libmvec/common/__vsin.c
  usr/src/lib/pam_modules/tsol_acct/tsol_acct.c
  usr/src/man/man1m/netstat.1m
  usr/src/pkg/Makefile
  usr/src/pkg/manifests/developer-build-onbld.mf
  usr/src/pkg/manifests/system-header.mf
  usr/src/tools/scripts/bldenv.sh
  usr/src/tools/scripts/check_rtime.1onbld
  usr/src/tools/scripts/check_rtime.pl
  usr/src/uts/common/fs/fdbuffer.c
  usr/src/uts/common/inet/ip/ip.c
  usr/src/uts/common/inet/ip/ip6.c
  usr/src/uts/common/inet/ip/ip_output.c
  usr/src/uts/common/inet/sctp/sctp_conn.c
  usr/src/uts/common/io/audio/impl/audio_sun.c
  usr/src/uts/common/syscall/auditsys.c
  usr/src/uts/common/syscall/uadmin.c
  usr/src/uts/i86pc/os/intr.c
  usr/src/uts/intel/Makefile.rules
  usr/src/uts/sun4u/makaha/Makefile
  usr/src/uts/sun4u/montecarlo/Makefile
Labels: backport-todo, upstream-merge

#194 Upstream merge r151026 backports
  usr/src/cmd/cmd-inet/usr.bin/netstat/netstat.c
  usr/src/cmd/smbsrv/smbd/server.xml
  usr/src/man/man1m/netstat.1m
  usr/src/tools/scripts/bldenv.sh
  usr/src/uts/common/sys/pci.h
  usr/src/uts/common/sys/pci_impl.h
  usr/src/uts/i86pc/io/vmm/amd/svm.c
  usr/src/uts/i86pc/io/vmm/intel/vmx.c
  usr/src/uts/i86pc/io/vmm/intel/vmx.h
  usr/src/uts/i86pc/io/vmm/io/ppt.c
  usr/src/uts/i86pc/io/vmm/vmm.c
  usr/src/uts/i86pc/sys/vmm.h
  usr/src/uts/intel/io/pci/pci_boot.c
  usr/src/uts/intel/io/pci/pci_pci.c
Labels: backport-PR, upstream-merge

#196 pxeboot fixes (r151026)
  usr/src/boot/sys/boot/common/dev_net.c
  usr/src/man/man5/pxeboot.5
Labels: backport-PR

#195 pxeboot fixes
  usr/src/boot/sys/boot/common/dev_net.c
  usr/src/man/man5/pxeboot.5
Labels: backport-todo, bug, upstream-candidate

#197 Upstream merge upstream_merge/2018041901
  usr/src/cmd/mdb/i86pc/modules/unix/i86mmu.c
  usr/src/cmd/zdb/zdb.c
  usr/src/cmd/ztest/ztest.c
  usr/src/lib/libzfs/common/libzfs_pool.c
  usr/src/lib/libzpool/common/llib-lzpool
  usr/src/test/os-tests/doc/README
  usr/src/uts/common/fs/autofs/auto_subr.c
  usr/src/uts/common/fs/smbclnt/smbfs/smbfs.h
  usr/src/uts/common/fs/smbclnt/smbfs/smbfs_vfsops.c
  usr/src/uts/common/fs/smbclnt/smbfs/smbfs_vnops.c
  usr/src/uts/common/fs/zfs/dsl_scan.c
  usr/src/uts/common/fs/zfs/metaslab.c
  usr/src/uts/common/fs/zfs/spa.c
  usr/src/uts/common/fs/zfs/spa_misc.c
  usr/src/uts/common/fs/zfs/sys/vdev_removal.h
  usr/src/uts/common/fs/zfs/sys/zio.h
  usr/src/uts/common/fs/zfs/vdev.c
  usr/src/uts/common/fs/zfs/vdev_indirect.c
  usr/src/uts/common/fs/zfs/vdev_label.c
  usr/src/uts/common/fs/zfs/vdev_mirror.c
  usr/src/uts/common/fs/zfs/vdev_removal.c
  usr/src/uts/common/fs/zfs/zio.c
Labels: upstream-merge

#204 Backport 20180425 r26
  usr/src/cmd/bhyve/pci_passthru.c
  usr/src/cmd/boot/bootadm/bootadm.c
  usr/src/uts/common/io/nvme/nvme.c
  usr/src/uts/i86pc/io/viona/viona.c
  usr/src/uts/i86pc/io/vmm/io/ppt.c
Labels: backport-PR

#203 Joyent merge/2018042501
  README.OmniOS
  usr/src/cmd/bhyve/pci_passthru.c
  usr/src/uts/i86pc/io/viona/viona.c
  usr/src/uts/i86pc/io/vmm/io/ppt.c
Labels: backport-todo, upstream-merge
