Repository omniosorg/illumos-omnios, pull requests merged in 2019-07, with the labels that each got.

#507 Joyent merge/2019063001
  README.OmniOS
  usr/src/compat/freebsd/sys/cpuset.h
  usr/src/uts/common/brand/lx/syscall/lx_futex.c
  usr/src/uts/i86pc/io/vmm/amd/svm.c
  usr/src/uts/i86pc/io/vmm/intel/vmx.c
  usr/src/uts/i86pc/io/vmm/io/vioapic.c
  usr/src/uts/i86pc/io/vmm/io/vlapic.c
  usr/src/uts/i86pc/io/vmm/io/vlapic.h
  usr/src/uts/i86pc/io/vmm/io/vlapic_priv.h
  usr/src/uts/i86pc/io/vmm/vmm.c
  usr/src/uts/i86pc/io/vmm/vmm_sol_glue.c
  usr/src/uts/i86pc/io/vmm/vmm_stat.c
  usr/src/uts/i86pc/io/vmm/vmm_stat.h
  usr/src/uts/i86pc/os/cpuid.c
  usr/src/uts/i86pc/sys/vmm.h
Labels: backport-todo, upstream-merge

#510 Upstream merge/2019070501
  usr/src/cmd/acct/acctwtmp.c
  usr/src/cmd/audio/audioplay/audioplay.c
  usr/src/cmd/audio/audiorecord/audiorecord.c
  usr/src/cmd/bart/compare.c
  usr/src/cmd/boot/bootadm/bootadm.c
  usr/src/cmd/boot/bootadm/bootadm_hyper.c
  usr/src/cmd/dis/dis_util.c
  usr/src/cmd/mdb/common/mdb/mdb_cmds.c
  usr/src/cmd/mdb/common/mdb/mdb_demangle.c
  usr/src/cmd/sgs/elfdump/common/elfdump.msg
  usr/src/cmd/sgs/pvs/common/pvs.c
  usr/src/cmd/sgs/pvs/common/pvs.msg
  usr/src/lib/Makefile
  usr/src/lib/libcustr/common/custr.c
  usr/src/lib/libcustr/common/libcustr.h
  usr/src/lib/libcustr/common/mapfile-vers
  usr/src/lib/libdemangle/Makefile.com
  usr/src/lib/libdemangle/common/cxx.c
  usr/src/lib/libdemangle/common/demangle-sys.h
  usr/src/lib/libdemangle/common/demangle.c
  usr/src/lib/libdemangle/common/demangle_int.h
  usr/src/lib/libdemangle/common/rust.c
  usr/src/lib/libdemangle/common/strview.c
  usr/src/lib/libdemangle/common/strview.h
  usr/src/lib/libdemangle/common/util.c
  usr/src/lib/scsi/plugins/ses/ses2/common/ses2_element.c
  usr/src/man/man1/dis.1
  usr/src/man/man1/dump.1
  usr/src/man/man1/elfdump.1
  usr/src/man/man1/gprof.1
  usr/src/man/man1/nm.1
  usr/src/man/man1/pvs.1
  usr/src/pkg/manifests/system-test-utiltest.mf
  usr/src/test/util-tests/tests/demangle/Makefile
  usr/src/test/util-tests/tests/demangle/THIRDPARTYLICENSE.rust
  usr/src/test/util-tests/tests/demangle/THIRDPARTYLICENSE.rust.descrip
  usr/src/test/util-tests/tests/demangle/rust.c
Labels: upstream-merge

#513 Backports r30
  README.OmniOS
  usr/src/uts/common/inet/ip_ndp.h
Labels: backport-PR

#517 Re-synchronise template env files with upstream-gate (r151030)
  usr/src/tools/env/Makefile
  usr/src/tools/env/illumos.sh
  usr/src/tools/env/omnios-illumos-gate.sh
  usr/src/tools/env/omnios-illumos-omnios.sh
Labels: backport-PR

#519 Upstream merge upstream_merge/2019072401
  usr/src/cmd/keyserv/chkey_common.c
  usr/src/cmd/krb5/kadmin/dbutil/kadm5_create.c
  usr/src/cmd/krb5/kadmin/dbutil/kdb5_create.c
  usr/src/cmd/krb5/kadmin/kclient/kconf.c
  usr/src/cmd/krb5/kwarn/kwarnd_proc.c
  usr/src/cmd/logadm/main.c
  usr/src/cmd/logadm/tester
  usr/src/cmd/login/login.c
  usr/src/cmd/ls/ls.c
  usr/src/cmd/mail/isheader.c
  usr/src/cmd/mail/isit.c
  usr/src/cmd/man/man.c
  usr/src/cmd/mdb/common/mdb/mdb_fdio.c
  usr/src/cmd/msgfmt/msgfmt.c
  usr/src/cmd/msgfmt/xgettext.c
  usr/src/cmd/ndmpadm/ndmpadm_print.c
  usr/src/cmd/ndmpd/ndmp/ndmpd_callbacks.c
  usr/src/cmd/ndmpd/ndmp/ndmpd_log.c
  usr/src/cmd/spell/malloc.c
  usr/src/cmd/ypcmd/ypupdated.c
  usr/src/man/man3lib/libsysevent.3lib
  usr/src/man/man3sysevent/Makefile
  usr/src/man/man3sysevent/sysevents.3sysevent
  usr/src/pkg/manifests/system-header.mf
  usr/src/pkg/manifests/system-library-storage-libmpapi.mf
  usr/src/pkg/manifests/system-library.man3sysevent.inc
  usr/src/tools/Makefile
  usr/src/tools/scripts/nightly.sh
  usr/src/uts/common/io/ath/hal_x86_32.o.uu
  usr/src/uts/common/io/dls/dls_link.c
  usr/src/uts/common/io/dls/dls_mgmt.c
  usr/src/uts/common/io/vnic/vnic_dev.c
  usr/src/uts/common/sys/Makefile
  usr/src/uts/common/sys/dls.h
  usr/src/uts/common/sys/dls_impl.h
  usr/src/uts/common/sys/dls_mgmt.h
  usr/src/uts/common/sys/sysevent.h
  usr/src/uts/common/sys/sysevent/datalink.h
  usr/src/uts/common/sys/sysevent/eventdefs.h
  usr/src/uts/common/sys/vnic_impl.h
Labels: upstream-merge
