Repository omniosorg/illumos-omnios, pull requests merged in 2019-10, with the labels that each got.

#562 Upstream merge joyent_merge/2019100201
  README.OmniOS
  usr/contrib/freebsd/sys/linker_set.h
  usr/src/Makefile.master
  usr/src/cmd/bhyve/Makefile
  usr/src/compat/freebsd/sys/cdefs.h
  usr/src/pkg/manifests/developer-build-onbld.mf
  usr/src/tools/scripts/Makefile
  usr/src/tools/scripts/gensetdefs.pl
  usr/src/uts/i86pc/io/viona/viona_impl.h
  usr/src/uts/i86pc/io/viona/viona_main.c
  usr/src/uts/i86pc/io/viona/viona_ring.c
  usr/src/uts/i86pc/io/viona/viona_rx.c
  usr/src/uts/i86pc/io/viona/viona_tx.c
  usr/src/uts/i86pc/vmm/Makefile
Labels: upstream-merge

#575 Upstream merge upstream_merge/2019101701
  .gitignore
  usr/src/Makefile.master
  usr/src/boot/Makefile.version
  usr/src/boot/sys/boot/efi/loader/framebuffer.c
  usr/src/cmd/audio/audioconvert/Makefile
  usr/src/cmd/audio/utilities/AudioHdrParse.cc
  usr/src/cmd/audio/utilities/AudioTypeSampleRate.cc
  usr/src/cmd/audio/utilities/Makefile
  usr/src/cmd/make/bin/Makefile
  usr/src/cmd/make/bin/doname.cc
  usr/src/cmd/make/bin/files.cc
  usr/src/cmd/make/bin/implicit.cc
  usr/src/cmd/make/bin/main.cc
  usr/src/cmd/make/bin/read.cc
  usr/src/cmd/make/bin/read2.cc
  usr/src/cmd/make/include/mk/defs.h
  usr/src/cmd/make/include/mksh/misc.h
  usr/src/cmd/make/lib/mksh/Makefile
  usr/src/cmd/make/lib/mksh/dosys.cc
  usr/src/cmd/make/lib/vroot/Makefile
  usr/src/cmd/mdb/Makefile.kmdb.targ
  usr/src/cmd/mdb/Makefile.module
  usr/src/cmd/mdb/common/mdb/mdb_module.c
  usr/src/cmd/mdb/common/modules/genunix/genunix.c
  usr/src/cmd/smbsrv/smbd/server.xml
  usr/src/cmd/svc/milestone/fs-usr
  usr/src/cmd/svc/svcs/svcs.c
  usr/src/lib/libfru/Makefile.flag
  usr/src/lib/libnisdb/Makefile
  usr/src/lib/libnisdb/db_dictionary.cc
  usr/src/lib/libnisdb/db_mindex3.cc
  usr/src/lib/sun_fc/Makefile.com
  usr/src/lib/sun_fc/common/FCHBAPort.cc
  usr/src/lib/sun_fc/common/Lockable.cc
  usr/src/pkg/manifests/system-test-cryptotest.mf
  usr/src/test/crypto-tests/runfiles/default.run
  usr/src/test/crypto-tests/tests/digest/Makefile
  usr/src/test/crypto-tests/tests/digest/md5.c
  usr/src/tools/make/bin/Makefile
  usr/src/tools/make/lib/mksh/Makefile
  usr/src/tools/make/lib/vroot/Makefile
  usr/src/uts/Makefile.uts
  usr/src/uts/common/Makefile.rules
  usr/src/uts/common/fs/smbsrv/smb2_negotiate.c
  usr/src/uts/common/inet/kssl/ksslrec.c
  usr/src/uts/common/io/bnxe/577xx/common/bnxe_clc.c
  usr/src/uts/common/io/bnxe/577xx/hsi/hw/include/clc.h
  usr/src/uts/common/io/gld.c
  usr/src/uts/common/xen/io/xdf.c
  usr/src/uts/common/xen/io/xencons.c
  usr/src/uts/intel/klmmod/Makefile
  usr/src/uts/intel/klmops/Makefile
  usr/src/uts/intel/sda/Makefile
  usr/src/uts/sparc/klmmod/Makefile
  usr/src/uts/sparc/klmops/Makefile
Labels: upstream-merge

#577 Upstream merge/2019102001
  usr/src/cmd/smbsrv/smbd/smbd_authsvc.c
  usr/src/lib/libmlrpc/common/ndr_process.c
  usr/src/lib/libpcidb/common/pcidb.c
  usr/src/uts/common/fs/smbsrv/smb2_dispatch.c
  usr/src/uts/common/fs/smbsrv/smb2_setinfo_file.c
  usr/src/uts/common/fs/smbsrv/smb_ofile.c
  usr/src/uts/common/fs/smbsrv/smb_server.c
  usr/src/uts/common/fs/smbsrv/smb_session.c
  usr/src/uts/common/fs/smbsrv/smb_set_fileinfo.c
  usr/src/uts/common/fs/smbsrv/smb_srv_oplock.c
  usr/src/uts/common/fs/smbsrv/smb_tree_connect.c
  usr/src/uts/common/fs/smbsrv/smb_user.c
  usr/src/uts/common/smbsrv/smb_kproto.h
  usr/src/uts/common/smbsrv/smb_ktypes.h
Labels: backport-todo, upstream-merge

#578 SMB backports to r151032
  usr/src/cmd/smbsrv/smbd/smbd_authsvc.c
  usr/src/lib/libmlrpc/common/ndr_process.c
  usr/src/uts/common/fs/smbsrv/smb2_dispatch.c
  usr/src/uts/common/fs/smbsrv/smb2_negotiate.c
  usr/src/uts/common/fs/smbsrv/smb2_setinfo_file.c
  usr/src/uts/common/fs/smbsrv/smb_ofile.c
  usr/src/uts/common/fs/smbsrv/smb_server.c
  usr/src/uts/common/fs/smbsrv/smb_session.c
  usr/src/uts/common/fs/smbsrv/smb_set_fileinfo.c
  usr/src/uts/common/fs/smbsrv/smb_srv_oplock.c
  usr/src/uts/common/fs/smbsrv/smb_tree_connect.c
  usr/src/uts/common/fs/smbsrv/smb_user.c
  usr/src/uts/common/smbsrv/smb_kproto.h
  usr/src/uts/common/smbsrv/smb_ktypes.h
Labels: backport-PR
