Repository omniosorg/illumos-omnios, pull requests merged in 2019-01, with the labels that each got.

#359 Loader and brand improvements
  usr/src/boot/sys/boot/common/help.common
  usr/src/boot/sys/boot/common/interp.c
  usr/src/boot/sys/boot/forth/beadm.4th
  usr/src/boot/sys/boot/forth/brand-omnios.4th
  usr/src/boot/sys/boot/forth/check-password.4th
  usr/src/boot/sys/boot/forth/logo-omnios.4th
  usr/src/boot/sys/boot/forth/menu-commands.4th
  usr/src/boot/sys/boot/forth/menu.4th
  usr/src/boot/sys/boot/forth/menusets.4th
  usr/src/boot/sys/boot/forth/screen.4th
  usr/src/boot/sys/boot/forth/support.4th
  usr/src/boot/sys/boot/forth/version.4th
  usr/src/common/ficl/emu/loader_emu.c
  usr/src/common/ficl/ficl.h
  usr/src/common/ficl/tools.c
Labels: upstream-candidate

#361 Loader framebuffer updates
  exception_lists/packaging
  usr/src/boot/sys/boot/common/gfx_fb.c
  usr/src/boot/sys/boot/common/gfx_fb.h
  usr/src/boot/sys/boot/forth/Makefile.inc
  usr/src/boot/sys/boot/forth/dragon.png
  usr/src/boot/sys/boot/forth/dragonf.png
  usr/src/boot/sys/boot/forth/logo-illumos.4th
  usr/src/boot/sys/boot/forth/logo-omnios.4th
  usr/src/boot/sys/boot/forth/omnios.png
  usr/src/boot/sys/boot/forth/ooce.png
  usr/src/common/ficl/loader.c
  usr/src/man/man5/Makefile
  usr/src/man/man5/loader.5
  usr/src/pkg/manifests/system-boot-loader.mf
  usr/src/uts/common/sys/tem_impl.h
Labels: upstream-candidate

#363 Upstream merge joyent_merge/2019012001
  usr/src/uts/common/io/vioif/vioif.c
  usr/src/uts/common/os/zone.c
  usr/src/uts/i86pc/os/cmi_hw.c
  usr/src/uts/i86pc/os/cpuid.c
Labels: upstream-merge

#368 update tzdata to 2018i
  usr/src/data/zoneinfo/README.illumos
  usr/src/data/zoneinfo/africa
  usr/src/data/zoneinfo/asia
  usr/src/data/zoneinfo/australasia
  usr/src/data/zoneinfo/northamerica
  usr/src/data/zoneinfo/zone.tab.txt
  usr/src/data/zoneinfo/zone_sun.tab
  usr/src/pkg/manifests/system-data-zoneinfo.mf
Labels: backport-todo, upstream-candidate
