Repository omniosorg/illumos-omnios, pull requests merged in 2019-09, with the labels that each got.

#530 Upstream merge upstream_merge/2019083101
  usr/src/cmd/mdb/i86pc/modules/unix/unix.c
  usr/src/lib/fm/topo/libtopo/common/topo_hc.h
  usr/src/lib/fm/topo/maps/SMCI,SSG-2029P-ACR24L/SSG-2029P-ACR24L-disk-hc-topology.xmlgenksh
  usr/src/lib/fm/topo/modules/common/Makefile
  usr/src/lib/fm/topo/modules/common/fac_prov_ahci/Makefile
  usr/src/lib/fm/topo/modules/common/fac_prov_ahci/fac_prov_ahci.c
  usr/src/lib/libkmf/plugins/kmf_openssl/common/openssl_spi.c
  usr/src/lib/libzfs/Makefile.com
  usr/src/lib/libzfs/common/libzfs_impl.h
  usr/src/lib/libzfs/common/libzfs_pool.c
  usr/src/lib/libzfs/common/libzfs_util.c
  usr/src/man/man1/ld.1
  usr/src/man/man1m/fmadm.1m
  usr/src/man/man1m/fmstat.1m
  usr/src/man/man3c/thrd_join.3c
  usr/src/man/man3ext/SUNW_C_GetMechSession.3ext
  usr/src/man/man3lib/libpkcs11.3lib
  usr/src/man/man3proc/Pisprocdir.3proc
  usr/src/man/man5/privileges.5
  usr/src/pkg/manifests/service-fault-management.mf
  usr/src/uts/Makefile.uts
  usr/src/uts/common/brand/lx/syscall/lx_aio.c
  usr/src/uts/common/inet/tcp/tcp_timers.c
  usr/src/uts/common/io/comstar/port/qlt/qlt.c
  usr/src/uts/common/io/fibre-channel/fca/qlc/ql_fm.c
  usr/src/uts/common/io/fibre-channel/fca/qlc/ql_xioctl.c
  usr/src/uts/common/io/i40e/i40e_intr.c
  usr/src/uts/common/io/sata/adapters/ahci/ahci.c
  usr/src/uts/common/io/vioif/vioif.c
  usr/src/uts/common/io/vioif/vioif.h
  usr/src/uts/common/io/virtio/virtio_main.c
  usr/src/uts/common/sys/null.h
  usr/src/uts/i86pc/Makefile.rules
  usr/src/uts/intel/io/hyperv/vmbus/hyperv_busdma.c
  usr/src/uts/intel/io/hyperv/vmbus/vmbus.c
Labels: upstream-merge

#534 Upstream merge joyent_merge/2019091301
  .gitignore
  README.OmniOS
  usr/src/cmd/mdb/common/modules/genunix/Makefile.files
  usr/src/cmd/mdb/common/modules/genunix/genunix.c
  usr/src/cmd/mdb/common/modules/genunix/refstr.c
  usr/src/cmd/pgrep/Makefile
  usr/src/cmd/pgrep/idtab.c
  usr/src/cmd/pgrep/pgrep.c
  usr/src/cmd/pgrep/psexp.c
  usr/src/cmd/pgrep/psexp.h
  usr/src/cmd/ps/ps.c
  usr/src/cmd/ps/ucbps.c
  usr/src/cmd/ptools/ptree/ptree.c
  usr/src/man/man1/pgrep.1
  usr/src/man/man1/ps.1
  usr/src/man/man1/ptree.1
  usr/src/man/man1b/ps.1b
  usr/src/uts/common/brand/lx/os/lx_brand.c
  usr/src/uts/common/brand/lx/os/lx_misc.c
  usr/src/uts/common/brand/lx/procfs/lx_proc.h
  usr/src/uts/common/brand/lx/procfs/lx_prvnops.c
  usr/src/uts/common/brand/lx/sys/lx_brand.h
  usr/src/uts/common/brand/lx/sys/lx_misc.h
  usr/src/uts/common/contract/process.c
  usr/src/uts/common/fs/proc/prargv.c
  usr/src/uts/common/fs/proc/prdata.h
  usr/src/uts/common/fs/proc/prvnops.c
  usr/src/uts/common/inet/cc/cc_cubic.c
  usr/src/uts/common/io/aggr/aggr_grp.c
  usr/src/uts/common/io/mac/mac.c
  usr/src/uts/common/io/scsi/adapters/mpt_sas/mptsas_impl.c
  usr/src/uts/common/os/exec.c
  usr/src/uts/common/os/zone.c
  usr/src/uts/common/sys/exec.h
  usr/src/uts/common/sys/procfs.h
  usr/src/uts/common/sys/user.h
Labels: upstream-merge

#537 Generate /etc/versions/build from fragments
  usr/src/Makefile.master
  usr/src/Targetdirs
  usr/src/cmd/boot/bootadm/bootadm.c
  usr/src/cmd/nsadmin/Makefile
  usr/src/pkg/Makefile
  usr/src/pkg/manifests/SUNWcs.mf
Labels: upstream-candidate

#536 Add support for building with glib2 v2.62
  usr/src/cmd/hal/Makefile.hal
  usr/src/cmd/latencytop/Makefile.com
  usr/src/cmd/policykit/Makefile
  usr/src/lib/policykit/libpolkit/Makefile.com
Labels: upstream-candidate

#540 Upstream merge/2019091701
  usr/src/data/hwdata/pci.ids
  usr/src/data/hwdata/usb.ids
  usr/src/data/zoneinfo/africa
  usr/src/data/zoneinfo/antarctica
  usr/src/data/zoneinfo/asia
  usr/src/data/zoneinfo/australasia
  usr/src/data/zoneinfo/europe
  usr/src/data/zoneinfo/northamerica
  usr/src/data/zoneinfo/southamerica
  usr/src/data/zoneinfo/systemv
  usr/src/data/zoneinfo/zone.tab.txt
  usr/src/data/zoneinfo/zone_sun.tab
  usr/src/head/stdlib.h
  usr/src/lib/libc/amd64/Makefile
  usr/src/lib/libc/i386/Makefile.com
  usr/src/lib/libc/port/gen/reallocf.c
  usr/src/lib/libc/port/mapfile-vers
  usr/src/lib/libc/sparc/Makefile.com
  usr/src/lib/libc/sparcv9/Makefile.com
  usr/src/man/man3c/Makefile
  usr/src/man/man3c/malloc.3c
  usr/src/pkg/manifests/system-data-zoneinfo.mf
  usr/src/pkg/manifests/system-library.man3c.inc
Labels: upstream-merge

#544 LX: OS-7980 lx getsockopt should return EOPNOTSUPP when TCP options a…
  README.OmniOS
  usr/src/uts/common/brand/lx/syscall/lx_socket.c
Labels: backport-PR

#543 Upstream merge joyent_merge/2019091801
  README.OmniOS
  usr/src/uts/common/brand/lx/syscall/lx_socket.c
Labels: upstream-merge

#545 Upstream merge/2019091801
  usr/src/boot/Makefile.version
  usr/src/boot/sys/boot/efi/libefi/efi_console.c
  usr/src/boot/sys/boot/efi/loader/copy.c
  usr/src/boot/sys/boot/forth/support.4th
  usr/src/data/locale/README.txt
  usr/src/data/locale/data/common.UTF-8.src
  usr/src/data/locale/tools/utf8-rollup.pl
  usr/src/test/os-tests/tests/secflags/secflags_limits.sh
  usr/src/uts/common/fs/zfs/zvol.c
  usr/src/uts/common/io/strredirm.c
  usr/src/uts/common/io/telmod.c
Labels: upstream-merge
