Repository omniosorg/illumos-omnios, pull requests merged in 2020-09, with the labels that each got.

#839 Upstream Nexenta NDMP fixes
  usr/src/cmd/ndmpadm/ndmpadm_main.c
  usr/src/cmd/ndmpd/Makefile
  usr/src/cmd/ndmpd/include/ndmpd_prop.h
  usr/src/cmd/ndmpd/include/tlm.h
  usr/src/cmd/ndmpd/include/tlm_buffers.h
  usr/src/cmd/ndmpd/ndmp.xml
  usr/src/cmd/ndmpd/ndmp/ndmpd.h
  usr/src/cmd/ndmpd/ndmp/ndmpd_callbacks.c
  usr/src/cmd/ndmpd/ndmp/ndmpd_chkpnt.c
  usr/src/cmd/ndmpd/ndmp/ndmpd_clone.c
  usr/src/cmd/ndmpd/ndmp/ndmpd_comm.c
  usr/src/cmd/ndmpd/ndmp/ndmpd_common.h
  usr/src/cmd/ndmpd/ndmp/ndmpd_config.c
  usr/src/cmd/ndmpd/ndmp/ndmpd_connect.c
  usr/src/cmd/ndmpd/ndmp/ndmpd_data.c
  usr/src/cmd/ndmpd/ndmp/ndmpd_door.c
  usr/src/cmd/ndmpd/ndmp/ndmpd_dtime.c
  usr/src/cmd/ndmpd/ndmp/ndmpd_fhistory.c
  usr/src/cmd/ndmpd/ndmp/ndmpd_main.c
  usr/src/cmd/ndmpd/ndmp/ndmpd_mark.c
  usr/src/cmd/ndmpd/ndmp/ndmpd_mover.c
  usr/src/cmd/ndmpd/ndmp/ndmpd_prop.c
  usr/src/cmd/ndmpd/ndmp/ndmpd_scsi.c
  usr/src/cmd/ndmpd/ndmp/ndmpd_tape.c
  usr/src/cmd/ndmpd/ndmp/ndmpd_tar.c
  usr/src/cmd/ndmpd/ndmp/ndmpd_tar3.c
  usr/src/cmd/ndmpd/ndmp/ndmpd_util.c
  usr/src/cmd/ndmpd/ndmp/ndmpd_zfs.c
  usr/src/cmd/ndmpd/tlm/tlm_backup_reader.c
  usr/src/cmd/ndmpd/tlm/tlm_bitmap.c
  usr/src/cmd/ndmpd/tlm/tlm_hardlink.c
  usr/src/cmd/ndmpd/tlm/tlm_info.c
  usr/src/cmd/ndmpd/tlm/tlm_init.c
  usr/src/cmd/ndmpd/tlm/tlm_lib.c
  usr/src/cmd/ndmpd/tlm/tlm_proto.h
  usr/src/cmd/ndmpd/tlm/tlm_restore_writer.c
  usr/src/cmd/ndmpd/tlm/tlm_traverse.c
  usr/src/cmd/ndmpd/tlm/tlm_util.c
  usr/src/pkg/manifests/service-storage-ndmp.mf
Labels: upstream-candidate

#844 13167 Update hwdata to 2020.9.15 (r151030)
  usr/src/data/hwdata/pci.ids
  usr/src/data/hwdata/usb.ids
Labels: backport-PR

#850 Upstream merge upstream_merge/2020093001
  usr/src/man/man7d/igb.7d
  usr/src/test/os-tests/runfiles/default.run
  usr/src/uts/common/brand/lx/syscall/lx_futex.c
  usr/src/uts/common/inet/squeue.c
  usr/src/uts/common/inet/tcp/tcp_socket.c
  usr/src/uts/common/io/i40e/core/i40e_common.c
  usr/src/uts/common/io/i40e/i40e_gld.c
  usr/src/uts/common/io/i40e/i40e_sw.h
  usr/src/uts/common/mapfiles/mac.mapfile
Labels: upstream-merge
