Repository omniosorg/illumos-omnios, pull requests merged in 2020-05, with the labels that each got.

#733 Joyent merge/2020050101
  README.OmniOS
  usr/src/uts/common/brand/lx/os/lx_brand.c
  usr/src/uts/common/brand/lx/sys/lx_brand.h
Labels: backport-todo

#735 LX: OS-8165 dockerinit should be able to start lx_lockd (#297) (r151032)
  README.OmniOS
  usr/src/uts/common/brand/lx/os/lx_brand.c
  usr/src/uts/common/brand/lx/sys/lx_brand.h
Labels: backport-PR

#734 LX: OS-8165 dockerinit should be able to start lx_lockd (#297) (r151030)
  README.OmniOS
  usr/src/uts/common/brand/lx/os/lx_brand.c
  usr/src/uts/common/brand/lx/sys/lx_brand.h
Labels: backport-PR

#737 Upstream merge upstream_merge/2020050201
  exception_lists/check_rtime
  exception_lists/interface_check
  exception_lists/packaging
  usr/src/Makefile.master
  usr/src/Targetdirs
  usr/src/cmd/Adm/sun/Makefile
  usr/src/cmd/abi/appcert/scripts/abi_index.pl
  usr/src/cmd/init/Makefile
  usr/src/cmd/init/init.c
  usr/src/cmd/sgs/crle/common/crle.msg
  usr/src/cmd/sgs/rtld/common/a.out.c
  usr/src/cmd/sgs/rtld/common/rtld.sparc32.msg
  usr/src/cmd/smbios/smbios.c
  usr/src/cmd/w/w.c
  usr/src/cmd/whodo/whodo.c
  usr/src/cmd/zpool/zpool_main.c
  usr/src/common/acl/acl_common.c
  usr/src/common/bootbanner/bootbanner.c
  usr/src/lib/libzfs/common/libzfs_pool.c
  usr/src/man/man1/crle.1
  usr/src/man/man1m/zpool.1m
  usr/src/man/man2/sysinfo.2
  usr/src/man/man5/filesystem.5
  usr/src/pkg/manifests/system-test-zfstest.mf
  usr/src/test/zfs-tests/runfiles/omnios.run
  usr/src/test/zfs-tests/runfiles/openindiana.run
  usr/src/test/zfs-tests/runfiles/smartos.run
  usr/src/test/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_features_004_neg.ksh
  usr/src/test/zfs-tests/tests/functional/cli_root/zpool_create/zpool_create_features_005_pos.ksh
  usr/src/tools/scripts/bldenv
  usr/src/tools/scripts/check_rtime.pl
  usr/src/tools/scripts/nightly
  usr/src/ucbcmd/Makefile.ucbcmd
  usr/src/uts/common/Makefile.files
  usr/src/uts/common/Makefile.rules
  usr/src/uts/common/io/cmlb.c
  usr/src/uts/common/io/mlxcx/mlxcx.c
  usr/src/uts/common/io/mlxcx/mlxcx.h
  usr/src/uts/common/io/mlxcx/mlxcx_gld.c
  usr/src/uts/common/io/mlxcx/mlxcx_ring.c
  usr/src/uts/common/os/logsubr.c
  usr/src/uts/common/sys/Makefile
  usr/src/uts/common/sys/bootbanner.h
  usr/src/uts/common/sys/smbios.h
  usr/src/uts/common/sys/systeminfo.h
  usr/src/uts/common/syscall/systeminfo.c
  usr/src/uts/sun4/os/machdep.c
Labels: upstream-merge

#742 Joyent merge/2020050501
  README.OmniOS
  usr/src/uts/common/brand/lx/os/lx_lockd.c
Labels: backport-todo

#745 OS-8167 lx_upcall_statd() may hang-or-panic when trying to upcall (r151034)
  README.OmniOS
  usr/src/uts/common/brand/lx/os/lx_lockd.c
Labels: backport-PR

#744 OS-8167 lx_upcall_statd() may hang-or-panic when trying to upcall (r151032)
  README.OmniOS
  usr/src/uts/common/brand/lx/os/lx_lockd.c
Labels: backport-PR

#743 OS-8167 lx_upcall_statd() may hang-or-panic when trying to upcall (r151030)
  README.OmniOS
  usr/src/uts/common/brand/lx/os/lx_lockd.c
Labels: backport-PR

#748 Backports for r151034
  usr/src/cmd/fs.d/nfs/lockd/lockd.c
  usr/src/lib/brand/lx/lx_lockd/lockd.c
  usr/src/lib/brand/lx/lx_lockd/nfs_tbind.c
  usr/src/tools/scripts/Makefile
  usr/src/uts/common/fs/nfs/nfs_sys.c
  usr/src/uts/common/klm/klmmod.c
  usr/src/uts/common/klm/nlm_impl.c
  usr/src/uts/common/klm/nlm_impl.h
  usr/src/uts/common/nfs/nfssys.h
Labels: backport-PR

#747 Backports for r151030
  usr/src/cmd/fs.d/nfs/lockd/lockd.c
  usr/src/lib/brand/lx/lx_lockd/lockd.c
  usr/src/lib/brand/lx/lx_lockd/nfs_tbind.c
  usr/src/tools/scripts/Makefile
  usr/src/uts/common/fs/nfs/nfs_sys.c
  usr/src/uts/common/klm/klmmod.c
  usr/src/uts/common/klm/nlm_impl.c
  usr/src/uts/common/klm/nlm_impl.h
  usr/src/uts/common/nfs/nfssys.h
Labels: backport-PR

#749 Backports for r151032
  usr/src/cmd/fs.d/nfs/lockd/lockd.c
  usr/src/lib/brand/lx/lx_lockd/lockd.c
  usr/src/lib/brand/lx/lx_lockd/nfs_tbind.c
  usr/src/tools/scripts/Makefile
  usr/src/uts/common/fs/nfs/nfs_sys.c
  usr/src/uts/common/klm/klmmod.c
  usr/src/uts/common/klm/nlm_impl.c
  usr/src/uts/common/klm/nlm_impl.h
  usr/src/uts/common/nfs/nfssys.h
Labels: backport-PR

#751 ONU should handle publisher name change with zones (r151034)
  usr/src/tools/scripts/onu.sh.in
Labels: backport-PR

#752 ONU should handle publisher name change with zones (r151032)
  usr/src/tools/scripts/onu.sh.in
Labels: backport-PR

#753 ONU should handle publisher name change with zones (r151030)
  usr/src/tools/scripts/onu.sh.in
Labels: backport-PR

#750 ONU should handle publisher name change with zones
  usr/src/tools/scripts/onu.sh.in
Labels: backport-todo, bug

#759 r151034 backports
  README.OmniOS
  usr/src/compat/freebsd/sys/callout.h
  usr/src/data/zoneinfo/africa
  usr/src/data/zoneinfo/asia
  usr/src/data/zoneinfo/backward
  usr/src/data/zoneinfo/europe
  usr/src/data/zoneinfo/northamerica
  usr/src/data/zoneinfo/zone.tab.txt
  usr/src/data/zoneinfo/zone_sun.tab
  usr/src/pkg/manifests/system-data-zoneinfo.mf
  usr/src/uts/common/io/i40e/i40e_transceiver.c
  usr/src/uts/common/io/mac/mac_provider.c
  usr/src/uts/common/io/vioif/vioif.c
  usr/src/uts/common/mapfiles/mac.mapfile
  usr/src/uts/common/sys/mac_provider.h
  usr/src/uts/i86pc/io/vmm/vmm_sol_glue.c
Labels: backport-PR

#760 Upstream merge joyent_merge/2020051301
  README.OmniOS
  usr/src/compat/freebsd/sys/callout.h
  usr/src/uts/i86pc/io/vmm/vmm_sol_glue.c
Labels: upstream-merge

#762 Upstream merge upstream_merge/2020051501
  .gitignore
  usr/src/cmd/mdb/sparc/modules/genunix/gcore_isadep.c
  usr/src/cmd/mdb/sparc/v9/genunix/Makefile
  usr/src/lib/libc/port/gen/sysconf.c
  usr/src/man/man3c/sysconf.3c
  usr/src/man/man9e/_fini.9e
  usr/src/man/man9e/ioctl.9e
  usr/src/pkg/manifests/system-test-zfstest.mf
  usr/src/test/zfs-tests/runfiles/delphix.run
  usr/src/test/zfs-tests/runfiles/omnios.run
  usr/src/test/zfs-tests/runfiles/openindiana.run
  usr/src/test/zfs-tests/runfiles/smartos.run
  usr/src/test/zfs-tests/tests/functional/resilver/Makefile
  usr/src/test/zfs-tests/tests/functional/resilver/cleanup.ksh
  usr/src/test/zfs-tests/tests/functional/resilver/resilver.cfg
  usr/src/test/zfs-tests/tests/functional/resilver/resilver_restart_001.ksh
  usr/src/test/zfs-tests/tests/functional/resilver/setup.ksh
  usr/src/test/zfs-tests/tests/functional/resilver/sysevent.c
  usr/src/uts/common/fs/zfs/dsl_scan.c
  usr/src/uts/common/fs/zfs/spa.c
  usr/src/uts/common/fs/zfs/sys/dsl_scan.h
  usr/src/uts/common/fs/zfs/sys/spa.h
  usr/src/uts/common/fs/zfs/sys/vdev.h
  usr/src/uts/common/fs/zfs/vdev.c
  usr/src/uts/common/io/bge/bge_main2.c
  usr/src/uts/common/io/mac/mac_client.c
  usr/src/uts/common/sys/sysconfig.h
  usr/src/uts/common/sys/unistd.h
  usr/src/uts/common/syscall/sysconfig.c
  usr/src/uts/sfmmu/vm/hat_sfmmu.c
  usr/src/uts/sun4u/io/sbbc.c
  usr/src/uts/sun4u/sbbc/Makefile
Labels: upstream-merge

#766 Upstream merge upstream_merge/2020052402
  exception_lists/cstyle
  exception_lists/hdrchk
  exception_lists/packaging
  exception_lists/wscheck
  usr/src/cmd/bhyve/Makefile
  usr/src/cmd/bhyve/acpi.c
  usr/src/cmd/bhyvectl/Makefile
  usr/src/cmd/mdb/common/modules/genunix/streams.c
  usr/src/cmd/mdb/intel/Makefile.kmdb
  usr/src/cmd/mdb/intel/mdb/proc_ia32dep.c
  usr/src/head/Makefile
  usr/src/lib/libbe/common/libbe.h
  usr/src/lib/libc/port/stdio/ftell.c
  usr/src/man/man1/cp.1
  usr/src/man/man1/elfedit.1
  usr/src/man/man1/mail.1
  usr/src/man/man1/mdb.1
  usr/src/man/man1/wait.1
  usr/src/man/man1m/ipf.1m
  usr/src/man/man1m/luxadm.1m
  usr/src/man/man4/proc.4
  usr/src/man/man5/lf64.5
  usr/src/man/man7d/ecpp.7d
  usr/src/man/man7d/usbprn.7d
  usr/src/pkg/manifests/system-bhyve-tests.mf
  usr/src/pkg/manifests/system-bhyve.mf
  usr/src/pkg/manifests/system-header.mf
  usr/src/pkg/manifests/system-library-bhyve.mf
  usr/src/pkg/manifests/system-test-libctest.mf
  usr/src/pkg/manifests/system-test-zfstest.mf
  usr/src/test/libc-tests/runfiles/default.run
  usr/src/test/libc-tests/tests/stdio/Makefile
  usr/src/test/libc-tests/tests/stdio/ftello_12768.c
  usr/src/test/zfs-tests/runfiles/omnios.run
  usr/src/test/zfs-tests/runfiles/openindiana.run
  usr/src/test/zfs-tests/runfiles/smartos.run
  usr/src/test/zfs-tests/tests/functional/resilver/Makefile
  usr/src/test/zfs-tests/tests/functional/resilver/resilver_restart_001.ksh
  usr/src/test/zfs-tests/tests/functional/resilver/resilver_restart_002.ksh
  usr/src/test/zfs-tests/tests/functional/resilver/sysevent.c
  usr/src/uts/common/fs/zfs/dsl_scan.c
  usr/src/uts/common/fs/zfs/vdev.c
  usr/src/uts/common/io/simnet/simnet.c
  usr/src/uts/common/io/simnet/simnet_impl.h
  usr/src/uts/i86pc/io/vmm/amd/svm.c
  usr/src/uts/i86pc/io/vmm/intel/vmx.c
  usr/src/uts/i86pc/io/vmm/vm/vm_page.h
  usr/src/uts/i86pc/io/vmm/x86.c
  usr/src/uts/i86pc/io/vmm/x86.h
  usr/src/uts/i86pc/ppt/Makefile
  usr/src/uts/i86pc/sys/Makefile
  usr/src/uts/i86pc/vmm/Makefile
  usr/src/uts/intel/ia32/ml/modstubs.s
Labels: upstream-merge
