Repository omniosorg/illumos-omnios, pull requests merged in 2020-04, with the labels that each got.

#694 12260 Fix zpool history unbounded memory usage (r151030)
  README.OmniOS
  usr/src/cmd/zpool/zpool_main.c
  usr/src/lib/libzfs/common/libzfs.h
  usr/src/lib/libzfs/common/libzfs_pool.c
Labels: backport-PR

#695 Upstream merge r151034 backports
  usr/src/cmd/Makefile
  usr/src/cmd/demangle/Makefile
  usr/src/cmd/demangle/demangle.c
  usr/src/lib/commpage/amd64/cp_subr.s
  usr/src/lib/commpage/common/cp_main.c
  usr/src/lib/commpage/i386/cp_subr.s
  usr/src/lib/libdemangle/common/demangle-sys.h
  usr/src/lib/libdemangle/common/demangle.c
  usr/src/lib/libdemangle/common/mapfile-vers
  usr/src/man/man1/Makefile
  usr/src/man/man1/demangle.1
  usr/src/pkg/manifests/developer-object-file.mf
  usr/src/uts/common/fs/zfs/spa.c
  usr/src/uts/common/fs/zfs/sys/spa.h
  usr/src/uts/common/fs/zfs/sys/spa_boot.h
  usr/src/uts/common/fs/zfs/sys/vdev_impl.h
  usr/src/uts/common/fs/zfs/vdev_disk.c
  usr/src/uts/common/fs/zfs/zfs_vfsops.c
  usr/src/uts/common/os/devcfg.c
  usr/src/uts/common/sys/ddi_implfuncs.h
  usr/src/uts/intel/zfs/spa_boot.c
  usr/src/uts/sparc/zfs/spa_boot.c
Labels: upstream-merge

#707 11972 resync smatch [fix false positive in mac_sched] (r151034)
  usr/src/uts/intel/mac/Makefile
Labels: backport-PR

#708 Joyent merge/2020041001
  .gitignore
  README.OmniOS
  usr/src/lib/brand/lx/zone/Makefile
  usr/src/lib/brand/lx/zone/lx_boot.ksh
  usr/src/lib/brand/lx/zone/lx_boot_zone_void.ksh
  usr/src/pkg/manifests/system-zones-brand-lx.mf
  usr/src/uts/common/brand/lx/procfs/lx_prvnops.c
  usr/src/uts/common/brand/lx/syscall/lx_socket.c
Labels: upstream-merge

#709 GZ IP interfaces over overlay vnics are down after boot
  usr/src/cmd/svc/milestone/net-physical
Labels: backport-todo

#710 GZ IP interfaces over overlay vnics are down after boot (r151034)
  usr/src/cmd/svc/milestone/net-physical
Labels: backport-PR

#716 Upstream merge/2020041601
  usr/src/boot/sys/boot/forth/loader.4th
  usr/src/common/bignum/sun4u/mont_mulf_kernel_v9.s
  usr/src/data/Makefile.data
  usr/src/data/terminfo/Makefile
  usr/src/man/man1m/nfsd.1m
  usr/src/man/man4/nfs.4
  usr/src/man/man5/zones.5
  usr/src/man/man7d/mlxcx.7d
  usr/src/man/man7fs/sharefs.7fs
  usr/src/pkg/manifests/system-data-terminfo.mf
  usr/src/test/util-tests/tests/find/findtest.ksh
  usr/src/uts/common/fs/zfs/spa.c
  usr/src/uts/common/io/mlxcx/mlxcx.c
  usr/src/uts/common/io/mlxcx/mlxcx.conf
  usr/src/uts/common/io/mlxcx/mlxcx.h
  usr/src/uts/common/io/mlxcx/mlxcx_gld.c
  usr/src/uts/common/io/mlxcx/mlxcx_intr.c
  usr/src/uts/common/io/mlxcx/mlxcx_reg.h
  usr/src/uts/common/io/mlxcx/mlxcx_ring.c
  usr/src/uts/common/io/openprom.c
  usr/src/uts/sun4u/bignum/Makefile
Labels: upstream-merge

#723 Upstream merge/2020042101
  usr/src/cmd/devfsadm/i386/misc_link_i386.c
  usr/src/cmd/w/w.c
  usr/src/cmd/whodo/whodo.c
  usr/src/lib/fm/topo/modules/sun4v/chip/chip_sun4v.c
  usr/src/lib/fm/topo/modules/sun4v/hostbridge/hb_sun4v.c
  usr/src/pkg/manifests/driver-network-mlxcx.mf
  usr/src/psm/stand/boot/common/heap_kmem.c
  usr/src/psm/stand/boot/common/readfile.c
  usr/src/psm/stand/cpr/sparcv9/sun4u/machdep.c
  usr/src/psm/stand/cpr/sparcv9/sun4u/util.c
  usr/src/stand/lib/fs/hsfs/hsfsops.c
  usr/src/stand/lib/fs/nfs/auth_unix.c
  usr/src/stand/lib/fs/nfs/bootparams.c
  usr/src/stand/lib/fs/nfs/clnt_btcp.c
  usr/src/stand/lib/fs/nfs/clnt_budp.c
  usr/src/stand/lib/fs/nfs/getdents.c
  usr/src/stand/lib/fs/nfs/getdents3.c
  usr/src/stand/lib/fs/nfs/lookup.c
  usr/src/stand/lib/fs/nfs/mount.c
  usr/src/stand/lib/fs/nfs/nfs4ops.c
  usr/src/stand/lib/fs/nfs/pmap.c
  usr/src/stand/lib/fs/nfs/rpc.c
  usr/src/stand/lib/fs/ufs/lufsboot.c
  usr/src/stand/lib/fs/ufs/ufsops.c
  usr/src/stand/lib/inet/ipv4.c
  usr/src/stand/lib/tcp/Makefile
  usr/src/stand/lib/tcp/tcp.c
  usr/src/test/crypto-tests/tests/Makefile.crypto
  usr/src/test/crypto-tests/tests/digest/Makefile
  usr/src/uts/common/rpc/xdr.c
Labels: upstream-merge

#730 /etc/ppt_aliases needs to be in the boot archive
  usr/src/cmd/boot/filelist/i386/filelist.ramdisk
Labels: backport-PR

#729 /etc/ppt_aliases needs to be in the boot archive
  usr/src/cmd/boot/filelist/i386/filelist.ramdisk
Labels: backport-todo

#731 Backports to r151034
  usr/src/cmd/modload/Makefile
  usr/src/cmd/modload/Makefile.com
  usr/src/cmd/modload/addrem.h
  usr/src/cmd/modload/amd64/Makefile
  usr/src/cmd/modload/drvsubr.c
  usr/src/cmd/modload/plcysubr.c
  usr/src/cmd/modload/sparcv9/Makefile
  usr/src/lib/libzonecfg/common/libzonecfg.c
  usr/src/uts/common/brand/lx/os/lx_brand.c
  usr/src/uts/common/brand/lx/sys/lx_brand.h
Labels: upstream-merge
