Repository omniosorg/illumos-omnios, pull requests merged in 2020-12, with the labels that each got.

#896 Upstream merge upstream_merge/2020120401
  usr/src/Makefile.master
  usr/src/boot/Makefile.version
  usr/src/boot/lib/libstand/zfs/zfs.c
  usr/src/cmd/ctfconvert/ctfconvert.c
  usr/src/cmd/spell/Makefile
  usr/src/cmd/spell/spellin.c
  usr/src/cmd/zoneadmd/vplat.c
  usr/src/lib/crt/common/common-crt.c
  usr/src/lib/libctf/common/ctf_convert.c
  usr/src/lib/libctf/common/ctf_dwarf.c
  usr/src/lib/libctf/common/libctf.h
  usr/src/lib/libctf/common/libctf_impl.h
  usr/src/lib/libctf/common/mapfile-vers
  usr/src/tools/ctf/Makefile
  usr/src/tools/ctf/Makefile.ctf.post
  usr/src/tools/ctf/Makefile.ctf.targ
  usr/src/tools/ctf/common/list.c
  usr/src/tools/ctf/common/list.h
  usr/src/tools/ctf/common/utils.c
  usr/src/tools/ctf/ctfconvert/Makefile
  usr/src/tools/ctf/ctfconvert/Makefile.com
  usr/src/tools/ctf/ctfdiff/Makefile
  usr/src/tools/ctf/ctfdiff/Makefile.com
  usr/src/tools/ctf/ctfdump/Makefile
  usr/src/tools/ctf/ctfdump/Makefile.com
  usr/src/tools/ctf/ctfmerge/Makefile
  usr/src/tools/ctf/ctfmerge/Makefile.com
  usr/src/tools/ctf/ctfstrip/Makefile
  usr/src/tools/ctf/ctfstrip/ctfstrip.c
  usr/src/tools/ctf/dwarf/Makefile
  usr/src/tools/ctf/dwarf/Makefile.com
  usr/src/tools/ctf/libctf/Makefile
  usr/src/tools/ctf/libctf/Makefile.com
  usr/src/tools/ctf/stabs/Makefile
  usr/src/tools/ctf/stabs/Makefile.com
  usr/src/tools/ctf/stabs/common/fth_struct.c
  usr/src/tools/scripts/ctfconvert.1onbld
  usr/src/uts/common/fs/smbsrv/smb2_write.c
  usr/src/uts/common/fs/smbsrv/smb_common_open.c
  usr/src/uts/common/fs/smbsrv/smb_node.c
  usr/src/uts/common/fs/smbsrv/smb_ofile.c
  usr/src/uts/common/fs/smbsrv/smb_write.c
  usr/src/uts/common/fs/zfs/dmu_objset.c
  usr/src/uts/common/fs/zfs/zfs_ioctl.c
  usr/src/uts/common/fs/zfs/zfs_vfsops.c
  usr/src/uts/common/smbsrv/smb_ktypes.h
Labels: upstream-merge

#899 Backports to r151030
  usr/src/lib/crt/common/common-crt.c
  usr/src/uts/common/fs/smbsrv/smb2_read.c
Labels: backport-PR

#897 Backports to r151036
  usr/src/lib/crt/common/common-crt.c
  usr/src/uts/common/fs/smbsrv/smb2_read.c
  usr/src/uts/common/fs/smbsrv/smb2_write.c
  usr/src/uts/common/fs/smbsrv/smb_common_open.c
  usr/src/uts/common/fs/smbsrv/smb_node.c
  usr/src/uts/common/fs/smbsrv/smb_ofile.c
  usr/src/uts/common/fs/smbsrv/smb_write.c
  usr/src/uts/common/fs/zfs/dmu_objset.c
  usr/src/uts/common/fs/zfs/zfs_ioctl.c
  usr/src/uts/common/fs/zfs/zfs_vfsops.c
  usr/src/uts/common/smbsrv/smb_ktypes.h
Labels: backport-PR

#898 Backports to r151034
  usr/src/lib/crt/common/common-crt.c
  usr/src/uts/common/fs/smbsrv/smb2_read.c
  usr/src/uts/common/fs/zfs/dmu_objset.c
  usr/src/uts/common/fs/zfs/zfs_ioctl.c
  usr/src/uts/common/fs/zfs/zfs_vfsops.c
Labels: backport-PR

#902 13358 dmu_objset_upgrade_stop() needs to wait (r151034)
  usr/src/test/test-runner/cmd/run
  usr/src/uts/common/fs/zfs/dmu_objset.c
Labels: backport-PR

#901 13358 dmu_objset_upgrade_stop() needs to wait (r151036)
  usr/src/test/test-runner/cmd/run
  usr/src/uts/common/fs/zfs/dmu_objset.c
Labels: backport-PR

#903 Upstream merge/2020121301
  usr/src/boot/Makefile.version
  usr/src/boot/lib/libstand/zfs/nvlist.c
  usr/src/boot/sys/boot/common/gfx_fb.c
  usr/src/boot/sys/boot/i386/libi386/vbe.h
  usr/src/boot/sys/boot/i386/libi386/vidconsole.c
  usr/src/head/grp.h
  usr/src/lib/libc/port/gen/initgroups.c
  usr/src/lib/libc/port/mapfile-vers
  usr/src/man/man3c/Makefile
  usr/src/man/man3c/getgrouplist.3c
  usr/src/pkg/manifests/system-library.man3c.inc
  usr/src/uts/common/io/aggr/aggr_grp.c
  usr/src/uts/common/io/mlxcx/mlxcx.c
  usr/src/uts/common/sys/aggr_impl.h
  usr/src/uts/i86pc/io/vmm/vmm_lapic.c
Labels: backport-todo, upstream-merge
