Repository omniosorg/illumos-omnios, pull requests merged in 2020-11, with the labels that each got.

#886 Update Intel microcode to 20201118, build gate with openjdk11
  usr/src/data/ucode/intel/000806C1-80
  usr/src/pkg/manifests/system-microcode-intel.mf
  usr/src/tools/env/omnios-illumos-gate.sh
Labels: backport-todo

#887 Update Microcode, build gate with openjdk11 (r151036)
  usr/src/data/ucode/intel/000806C1-80
  usr/src/pkg/manifests/system-microcode-intel.mf
  usr/src/tools/env/omnios-illumos-gate.sh
Labels: backport-PR

#888 Update Intel microcode to 20201118 (r151034)
  usr/src/data/ucode/intel/000806C1-80
  usr/src/pkg/manifests/system-microcode-intel.mf
Labels: backport-PR

#889 Update Intel microcode to 20201118 (r151030)
  usr/src/data/ucode/intel/000806C1-80
  usr/src/pkg/manifests/system-kernel-platform.mf
Labels: backport-PR

#890 Upstream merge/2020112601
  README.OmniOS
  usr/src/Makefile.master
  usr/src/boot/Makefile.version
  usr/src/boot/sys/boot/common/console.c
  usr/src/boot/sys/boot/common/gfx_fb.c
  usr/src/boot/sys/boot/common/gfx_fb.h
  usr/src/cmd/zpool/Makefile
  usr/src/common/ficl/emu/gfx_fb.h
  usr/src/common/ficl/loader.c
  usr/src/lib/libc/port/threads/thr.c
  usr/src/lib/libdtrace_jni/java/Makefile
  usr/src/pkg/manifests/developer-dtrace.mf
  usr/src/test/util-tests/tests/ctf/check-forward.c
  usr/src/uts/i86pc/io/vmm/amd/svm.c
  usr/src/uts/i86pc/io/vmm/amd/vmcb.h
  usr/src/uts/i86pc/io/vmm/intel/vmx.c
  usr/src/uts/i86pc/io/vmm/intel/vmx.h
  usr/src/uts/i86pc/io/vmm/io/vioapic.c
  usr/src/uts/i86pc/io/vmm/io/vlapic.c
  usr/src/uts/i86pc/io/vmm/io/vlapic.h
  usr/src/uts/i86pc/io/vmm/io/vlapic_priv.h
  usr/src/uts/i86pc/io/vmm/sys/vmm_kernel.h
  usr/src/uts/i86pc/io/vmm/vmm.c
  usr/src/uts/i86pc/io/vmm/vmm_lapic.c
  usr/src/uts/i86pc/sys/vmm.h
Labels: backport-todo, upstream-merge

#891 13315 jdk11 makes consistent javadoc generation impossible (r151036)
  usr/src/lib/libdtrace_jni/java/Makefile
  usr/src/pkg/manifests/developer-dtrace.mf
Labels: backport-PR
