Repository omniosorg/illumos-omnios, pull requests merged in 2020-10, with the labels that each got.

#859 Upstream merge/2020100801
  usr/src/boot/lib/libstand/pager.c
  usr/src/boot/sys/boot/common/gfx_fb.h
  usr/src/boot/sys/boot/i386/libi386/vbe.c
  usr/src/boot/sys/boot/i386/libi386/vbe.h
  usr/src/man/man2/rename.2
  usr/src/man/man2/statvfs.2
  usr/src/man/man7d/pchtemp.7d
  usr/src/pkg/manifests/driver-cpu-sensor.mf
  usr/src/test/net-tests/tests/net_common.ksh
  usr/src/test/os-tests/runfiles/default.run
  usr/src/uts/common/inet/ipclassifier.h
  usr/src/uts/i86pc/io/rootnex.c
  usr/src/uts/intel/io/pchtemp/pchtemp.c
Labels: backport-todo, upstream-merge

#860 backports to r36
  usr/src/cmd/oamuser/user/funcs.c
  usr/src/cmd/oamuser/user/userdefs.c
  usr/src/cmd/oamuser/user/userdisp.h
  usr/src/cmd/passmgmt/Makefile
  usr/src/cmd/passmgmt/passmgmt.c
  usr/src/cmd/su/Makefile
  usr/src/cmd/su/su.c
  usr/src/head/user_attr.h
  usr/src/head/userdefs.h
  usr/src/man/man4/user_attr.4
  usr/src/man/man7d/pchtemp.7d
  usr/src/pkg/manifests/driver-cpu-sensor.mf
  usr/src/uts/intel/io/pchtemp/pchtemp.c
Labels: backport-PR

#863 Upstream merge/2020101701
  exception_lists/check_rtime
  exception_lists/interface_check
  usr/src/boot/Makefile.version
  usr/src/boot/sys/boot/i386/common/edd.h
  usr/src/cmd/zdb/zdb.c
  usr/src/lib/libzfs/common/libzfs_import.c
  usr/src/man/man1m/zdb.1m
  usr/src/pkg/manifests/system-test-zfstest.mf
  usr/src/test/zfs-tests/include/libtest.shlib
  usr/src/test/zfs-tests/runfiles/omnios.run
  usr/src/test/zfs-tests/runfiles/openindiana.run
  usr/src/test/zfs-tests/runfiles/smartos.run
  usr/src/test/zfs-tests/tests/functional/cache/cache_012_pos.ksh
  usr/src/test/zfs-tests/tests/functional/persist_l2arc/Makefile
  usr/src/test/zfs-tests/tests/functional/persist_l2arc/cleanup.ksh
  usr/src/test/zfs-tests/tests/functional/persist_l2arc/persist_l2arc.cfg
  usr/src/test/zfs-tests/tests/functional/persist_l2arc/persist_l2arc_001_pos.ksh
  usr/src/test/zfs-tests/tests/functional/persist_l2arc/persist_l2arc_002_pos.ksh
  usr/src/test/zfs-tests/tests/functional/persist_l2arc/persist_l2arc_003_neg.ksh
  usr/src/test/zfs-tests/tests/functional/persist_l2arc/persist_l2arc_004_pos.ksh
  usr/src/test/zfs-tests/tests/functional/persist_l2arc/persist_l2arc_005_pos.ksh
  usr/src/test/zfs-tests/tests/functional/persist_l2arc/persist_l2arc_006_pos.ksh
  usr/src/test/zfs-tests/tests/functional/persist_l2arc/persist_l2arc_007_pos.ksh
  usr/src/test/zfs-tests/tests/functional/persist_l2arc/persist_l2arc_008_pos.ksh
  usr/src/test/zfs-tests/tests/functional/persist_l2arc/setup.ksh
  usr/src/tools/scripts/wsdiff.py
  usr/src/uts/common/fs/zfs/arc.c
  usr/src/uts/common/fs/zfs/spa.c
  usr/src/uts/common/fs/zfs/sys/arc.h
  usr/src/uts/common/fs/zfs/sys/arc_impl.h
  usr/src/uts/common/fs/zfs/sys/spa.h
  usr/src/uts/common/fs/zfs/vdev.c
  usr/src/uts/common/inet/udp/udp.c
  usr/src/uts/common/sys/fs/zfs.h
  usr/src/uts/i86pc/Makefile.i86pc
  usr/src/uts/i86pc/io/vmm/intel/vmx_msr.c
  usr/src/uts/i86pc/unix/Makefile
  usr/src/uts/i86xpv/Makefile.i86xpv
  usr/src/uts/i86xpv/unix/Makefile
  usr/src/uts/sun4u/Makefile.sun4u
  usr/src/uts/sun4u/opl/unix/Makefile
  usr/src/uts/sun4u/serengeti/unix/Makefile
  usr/src/uts/sun4u/unix/Makefile
  usr/src/uts/sun4v/Makefile.sun4v
  usr/src/uts/sun4v/unix/Makefile
Labels: upstream-merge

#862 Sync NDMP support with illumos-nexenta.
  usr/src/cmd/ndmpd/tlm/tlm_backup_reader.c
Labels: upstream-candidate

#870 Upstream merge upstream_merge/2020102201
  .gitignore
  usr/src/boot/sys/boot/i386/gptzfsboot/Makefile
  usr/src/cmd/Makefile
  usr/src/cmd/amdzen/Makefile
  usr/src/cmd/amdzen/udf.c
  usr/src/cmd/amdzen/usmn.c
  usr/src/cmd/mdb/common/modules/usba/prtusb.c
  usr/src/common/util/strtol.c
  usr/src/common/util/strtoll.c
  usr/src/common/util/strtoul.c
  usr/src/common/util/strtoull.c
  usr/src/lib/libdwarf/Makefile.com
  usr/src/lib/libpam/pam_framework.c
  usr/src/man/man7d/Makefile
  usr/src/man/man7d/amdnbtemp.7d
  usr/src/man/man7d/amdzen.7d
  usr/src/man/man7d/smntemp.7d
  usr/src/man/man7d/usmn.7d
  usr/src/man/man7d/vioblk.7d
  usr/src/man/man7d/vioif.7d
  usr/src/man/man7d/virtio.7d
  usr/src/man/man7d/zen_udf.7d
  usr/src/pkg/manifests/driver-cpu-amd-zen.mf
  usr/src/pkg/manifests/driver-cpu-sensor.mf
  usr/src/pkg/manifests/driver-developer-amd-zen.mf
  usr/src/pkg/manifests/driver-misc-virtio.mf
  usr/src/pkg/manifests/driver-network-vioif.mf
  usr/src/pkg/manifests/driver-storage-vioblk.mf
  usr/src/uts/common/fs/zfs/dmu_objset.c
  usr/src/uts/common/fs/zfs/spa.c
  usr/src/uts/common/fs/zfs/vdev.c
  usr/src/uts/common/io/usb/hcd/xhci/xhci.c
  usr/src/uts/common/os/policy.c
  usr/src/uts/common/sys/policy.h
  usr/src/uts/intel/Makefile.files
  usr/src/uts/intel/Makefile.intel
  usr/src/uts/intel/Makefile.rules
  usr/src/uts/intel/amdzen/Makefile
  usr/src/uts/intel/amdzen_stub/Makefile
  usr/src/uts/intel/io/amdf17nbdf/amdf17nbdf.c
  usr/src/uts/intel/io/amdzen/amdzen.c
  usr/src/uts/intel/io/amdzen/amdzen.conf
  usr/src/uts/intel/io/amdzen/amdzen.h
  usr/src/uts/intel/io/amdzen/amdzen_client.h
  usr/src/uts/intel/io/amdzen/amdzen_stub.c
  usr/src/uts/intel/io/amdzen/smntemp.c
  usr/src/uts/intel/io/amdzen/usmn.c
  usr/src/uts/intel/io/amdzen/usmn.h
  usr/src/uts/intel/io/amdzen/zen_udf.c
  usr/src/uts/intel/io/amdzen/zen_udf.h
  usr/src/uts/intel/smntemp/Makefile
  usr/src/uts/intel/usmn/Makefile
  usr/src/uts/intel/zen_udf/Makefile
Labels: upstream-merge

#873 Upstream merge upstream_merge/2020102901
  usr/src/boot/Makefile.version
  usr/src/boot/sys/boot/common/gfx_fb.c
  usr/src/boot/sys/boot/common/multiboot2.c
  usr/src/boot/sys/boot/common/tem.c
  usr/src/boot/sys/boot/i386/libi386/vbe.c
  usr/src/boot/sys/boot/i386/libi386/vbe.h
  usr/src/boot/sys/boot/i386/libi386/vidconsole.c
  usr/src/common/font/font.c
  usr/src/lib/libc/amd64/Makefile
  usr/src/lib/libc/amd64/unwind/unwind.c
  usr/src/lib/libc/amd64/unwind/unwind_wrap.s
  usr/src/pkg/manifests/developer-dtrace.mf
  usr/src/tools/env/omnios-illumos-gate.sh
  usr/src/tools/scripts/wsdiff.1onbld
  usr/src/tools/scripts/wsdiff.py
  usr/src/uts/common/c2/audit_io.c
  usr/src/uts/common/fs/zfs/dnode.c
  usr/src/uts/common/fs/zfs/sys/dmu_impl.h
  usr/src/uts/common/fs/zfs/sys/dnode.h
  usr/src/uts/common/fs/zfs/zfs_vnops.c
  usr/src/uts/common/io/mlxcx/mlxcx_cmd.c
  usr/src/uts/common/io/mlxcx/mlxcx_reg.h
  usr/src/uts/common/syscall/auditsys.c
Labels: upstream-merge
