Repository omniosorg/illumos-omnios, pull requests merged in 2021-09, with the labels that each got.

#1044 Upstream merge upstream_merge/2021090501
  .gitignore
  README.OmniOS
  usr/src/cmd/Makefile.cmd
  usr/src/cmd/Makefile.cmd.64
  usr/src/cmd/cmd-inet/usr.lib/in.mpathd/mpd_main.c
  usr/src/cmd/cmd-inet/usr.sbin/nwamcfg/Makefile
  usr/src/cmd/cmd-inet/usr.sbin/nwamcfg/nwamcfg.c
  usr/src/cmd/sgs/lorder/lorder.sh
  usr/src/lib/libipmp/common/ipmp_mpathd.c
  usr/src/lib/libipmp/common/ipmp_mpathd.h
  usr/src/lib/libipmp/common/ipmp_query.c
  usr/src/lib/libipmp/common/ipmp_query.h
  usr/src/lib/libipmp/common/ipmp_query_impl.h
  usr/src/man/man1m/acct.1m
  usr/src/man/man1m/chat.1m
  usr/src/man/man1m/format.1m
  usr/src/man/man1m/fsdb_udfs.1m
  usr/src/man/man1m/reboot.1m
  usr/src/man/man1m/route.1m
  usr/src/man/man1m/update_drv.1m
  usr/src/man/man3c/getgrouplist.3c
  usr/src/man/man3curses/forms.3curses
  usr/src/man/man3curses/menus.3curses
  usr/src/man/man3curses/panels.3curses
  usr/src/man/man3ldap/ldap_error.3ldap
  usr/src/man/man3rsm/rsm_memseg_import_set_mode.3rsm
  usr/src/man/man3sysevent/sysevents.3sysevent
  usr/src/man/man3tnf/tnfctl_indirect_open.3tnf
  usr/src/man/man7d/vioblk.7d
  usr/src/man/man7d/wscons.7d
  usr/src/man/man7i/mtio.7i
  usr/src/man/man9f/ddi_io_rep_get8.9f
  usr/src/uts/i86pc/io/viona/viona_ring.c
  usr/src/uts/i86pc/io/viona/viona_rx.c
  usr/src/uts/i86pc/io/vmm/vmm_gpt.c
  usr/src/uts/i86pc/io/vmm/vmm_sol_dev.c
Labels: upstream-merge

#1045 bhyve backports to r151038
  README.OmniOS
  exception_lists/cstyle
  exception_lists/packaging
  exception_lists/wscheck
  usr/src/cmd/bhyve/Makefile
  usr/src/cmd/bhyve/README.sync
  usr/src/cmd/bhyve/pci_virtio_9p.c
  usr/src/lib/Makefile
  usr/src/lib/lib9p/COPYRIGHT
  usr/src/lib/lib9p/COPYRIGHT.descrip
  usr/src/lib/lib9p/Makefile
  usr/src/lib/lib9p/Makefile.com
  usr/src/lib/lib9p/amd64/Makefile
  usr/src/lib/lib9p/common/backend/backend.h
  usr/src/lib/lib9p/common/backend/fs.c
  usr/src/lib/lib9p/common/backend/fs.h
  usr/src/lib/lib9p/common/connection.c
  usr/src/lib/lib9p/common/fcall.h
  usr/src/lib/lib9p/common/fid.h
  usr/src/lib/lib9p/common/genacl.c
  usr/src/lib/lib9p/common/genacl.h
  usr/src/lib/lib9p/common/hashtable.c
  usr/src/lib/lib9p/common/hashtable.h
  usr/src/lib/lib9p/common/illumos_endian.h
  usr/src/lib/lib9p/common/lib9p.h
  usr/src/lib/lib9p/common/lib9p_impl.h
  usr/src/lib/lib9p/common/linux_errno.h
  usr/src/lib/lib9p/common/log.c
  usr/src/lib/lib9p/common/log.h
  usr/src/lib/lib9p/common/pack.c
  usr/src/lib/lib9p/common/request.c
  usr/src/lib/lib9p/common/rfuncs.c
  usr/src/lib/lib9p/common/rfuncs.h
  usr/src/lib/lib9p/common/sbuf/sbuf.c
  usr/src/lib/lib9p/common/sbuf/sbuf.h
  usr/src/lib/lib9p/common/threadpool.c
  usr/src/lib/lib9p/common/threadpool.h
  usr/src/lib/lib9p/common/transport/socket.c
  usr/src/lib/lib9p/common/transport/socket.h
  usr/src/lib/lib9p/common/utils.c
  usr/src/lib/lib9p/mapfile-vers
  usr/src/man/man1m/bhyve.1m
  usr/src/man/man4/bhyve_config.4
  usr/src/pkg/manifests/system-library-bhyve.mf
  usr/src/uts/i86pc/io/viona/viona_impl.h
  usr/src/uts/i86pc/io/viona/viona_main.c
  usr/src/uts/i86pc/io/viona/viona_ring.c
  usr/src/uts/i86pc/io/viona/viona_rx.c
  usr/src/uts/i86pc/io/viona/viona_tx.c
  usr/src/uts/i86pc/io/vmm/vmm_instruction_emul.c
  usr/src/uts/i86pc/io/vmm/vmm_sol_dev.c
Labels: backport-PR

#1048 Upstream merge/2021092201
  usr/src/boot/sys/boot/forth/support.4th
  usr/src/cmd/ast/Makefile.iffe
  usr/src/cmd/ast/libast/Makefile.iffe
  usr/src/cmd/ast/libast/amd64/conftab.c
  usr/src/cmd/ast/libast/amd64/conftab.h
  usr/src/cmd/ast/libast/i386/conftab.c
  usr/src/cmd/ast/libast/i386/conftab.h
  usr/src/cmd/ast/libast/mapfile-vers
  usr/src/cmd/ast/libast/sparc/conftab.c
  usr/src/cmd/ast/libast/sparc/conftab.h
  usr/src/cmd/ast/libast/sparcv9/conftab.c
  usr/src/cmd/ast/libast/sparcv9/conftab.h
  usr/src/cmd/ast/libshell/Makefile.iffe
  usr/src/cmd/make/bin/main.cc
  usr/src/cmd/picl/plugins/sun4u/enchilada/envd/envd.h
  usr/src/cmd/picl/plugins/sun4u/psvc/psvcplugin/psvcplugin.c
  usr/src/cmd/picl/plugins/sun4u/taco/envd/envd.h
  usr/src/cmd/scadm/sparc/mpxu/common/modem_setup.c
  usr/src/contrib/ast/src/lib/libast/comp/conf.sh
  usr/src/lib/krb5/plugins/kdb/ldap/Makefile.com
  usr/src/lib/libc/port/sys/eventfd.c
  usr/src/man/man3c/Makefile
  usr/src/man/man3c/eventfd.3c
  usr/src/pkg/manifests/system-library.man3c.inc
  usr/src/pkg/manifests/system-test-ostest.mf
  usr/src/test/os-tests/runfiles/default.run
  usr/src/test/os-tests/tests/Makefile
  usr/src/test/os-tests/tests/eventfd.c
  usr/src/tools/cw/cw.c
  usr/src/uts/common/fs/smbsrv/smb2_negotiate.c
  usr/src/uts/common/fs/smbsrv/smb_sd.c
  usr/src/uts/i86pc/Makefile.files
  usr/src/uts/i86pc/io/gfx_private/gfxp_bitmap.c
  usr/src/uts/i86pc/io/hpet_acpi.c
  usr/src/uts/i86pc/io/mp_platform_common.c
  usr/src/uts/i86pc/os/fakebop.c
  usr/src/uts/i86pc/os/tscc_hpet.c
  usr/src/uts/i86pc/sys/apic_timer.h
  usr/src/uts/i86pc/sys/hpet.h
  usr/src/uts/sun4u/sys/sbdpriv.h
Labels: upstream-merge, backport-todo

#1049 Upstream merge upstream_merge/2021092301
  .gitignore
  usr/src/lib/krb5/plugins/kdb/ldap/Makefile.com
  usr/src/uts/common/os/driver_lyr.c
  usr/src/uts/common/os/strsubr.c
  usr/src/uts/common/sys/sunldi_impl.h
  usr/src/uts/i86pc/Makefile.files
  usr/src/uts/i86pc/os/tscc_vmware.c
Labels: upstream-merge

#1054 14115 dumping to zvol on raidz will corrupt the pool (r151038)
  usr/src/uts/common/fs/zfs/vdev_raidz.c
  usr/src/uts/common/fs/zfs/zvol.c
Labels: backport-PR

#1055 14115 dumping to zvol on raidz will corrupt the pool (r151036)
  usr/src/uts/common/fs/zfs/vdev_raidz.c
  usr/src/uts/common/fs/zfs/zvol.c
Labels: backport-PR

#1056 Upstream merge upstream_merge/2021092901
  usr/src/boot/Makefile.version
  usr/src/boot/sys/boot/common/dev_net.c
  usr/src/cmd/bhyve/bhyverun.c
  usr/src/cmd/cmd-inet/usr.bin/tftp/Makefile
  usr/src/cmd/cmd-inet/usr.bin/tftp/main.c
  usr/src/cmd/cmd-inet/usr.bin/tftp/tftp.c
  usr/src/data/hwdata/pci.ids
  usr/src/data/hwdata/usb.ids
  usr/src/lib/libvmmapi/common/vmmapi.c
  usr/src/lib/libvmmapi/common/vmmapi.h
  usr/src/man/man1/ctfdump.1
  usr/src/man/man3c/mbrtoc16.3c
  usr/src/pkg/manifests/system-data-hardware-registry.mf
  usr/src/tools/cpcgen/Makefile
  usr/src/uts/common/fs/zfs/vdev_raidz.c
  usr/src/uts/common/fs/zfs/zvol.c
  usr/src/uts/common/os/dkioc_free_util.c
  usr/src/uts/i86pc/io/vmm/intel/vmx.c
  usr/src/uts/i86pc/io/vmm/sys/vmm_kernel.h
  usr/src/uts/i86pc/io/vmm/vmm.c
  usr/src/uts/i86pc/io/vmm/vmm_sol_dev.c
  usr/src/uts/i86pc/os/fakebop.c
  usr/src/uts/i86pc/sys/vmm_dev.h
Labels: upstream-merge
