Repository omniosorg/illumos-omnios, pull requests merged in 2022-12, with the labels that each got.

#1264 LX: FUTEX_WAIT_BITSET should support timeout being NULL
  usr/src/uts/common/brand/lx/syscall/lx_futex.c
Labels: backport-todo

#1263 LX: FUTEX_WAIT_BITSET should support timeout being NULL (r151044)
  usr/src/uts/common/brand/lx/syscall/lx_futex.c
Labels: backport-PR

#1266 LX: FUTEX_WAIT_BITSET should support timeout being NULL (r151042)
  usr/src/uts/common/brand/lx/syscall/lx_futex.c
Labels: backport-PR

#1267 LX: FUTEX_WAIT_BITSET should support timeout being NULL (r151038)
  usr/src/uts/common/brand/lx/syscall/lx_futex.c
Labels: backport-PR

#1270 15206 setcontext(2) should not restore %fsbase (r151044)
  usr/src/lib/libc/port/threads/sigaction.c
  usr/src/man/man2/getcontext.2
  usr/src/pkg/manifests/system-test-ostest.p5m
  usr/src/test/os-tests/runfiles/default.run
  usr/src/test/os-tests/tests/Makefile
  usr/src/test/os-tests/tests/ucontext.c
Labels: backport-PR

#1269 Upstream merge/2022120801
  usr/src/cmd/boot/bootadm/bootadm_loader.c
  usr/src/lib/libc/port/threads/sigaction.c
  usr/src/lib/libdladm/Makefile.com
  usr/src/lib/libdladm/common/libdliptun.c
  usr/src/lib/libdladm/common/libdlsim.c
  usr/src/lib/libdladm/common/libdlvnic.c
  usr/src/lib/libofmt/common/ofmt.c
  usr/src/man/man2/getcontext.2
  usr/src/man/man8/sharemgr.8
  usr/src/pkg/manifests/system-test-ostest.p5m
  usr/src/test/os-tests/runfiles/default.run
  usr/src/test/os-tests/tests/Makefile
  usr/src/test/os-tests/tests/ucontext.c
  usr/src/uts/common/fs/smbsrv/smb_node.c
  usr/src/uts/common/fs/smbsrv/smb_server.c
  usr/src/uts/common/fs/smbsrv/smb_session.c
  usr/src/uts/common/fs/smbsrv/smb_srv_oplock.c
Labels: upstream-merge, backport-todo

#1273 15175 Update intel CPU Microcode to 20221108 (r151042)
  usr/src/data/ucode/intel/000606C1-10
  usr/src/data/ucode/intel/000706E5-80
  usr/src/data/ucode/intel/000806C1-80
  usr/src/data/ucode/intel/000806D1-02
  usr/src/data/ucode/intel/000806EC-04
  usr/src/data/ucode/intel/00090661-01
  usr/src/data/ucode/intel/00090672-01
  usr/src/data/ucode/intel/000906A3-80
  usr/src/data/ucode/intel/000906ED-02
  usr/src/data/ucode/intel/000A0652-20
  usr/src/data/ucode/intel/000A0653-02
  usr/src/data/ucode/intel/000A0655-02
  usr/src/data/ucode/intel/000A0660-80
  usr/src/data/ucode/intel/000A0661-80
  usr/src/data/ucode/intel/000A0671-02
  usr/src/data/ucode/intel/000B0671-02
  usr/src/data/ucode/intel/Makefile.links
  usr/src/pkg/manifests/system-microcode-intel.p5m
Labels: backport-PR

#1272 15175 Update intel CPU Microcode to 20221108 (r151044)
  usr/src/data/ucode/intel/000606C1-10
  usr/src/data/ucode/intel/000706E5-80
  usr/src/data/ucode/intel/000806C1-80
  usr/src/data/ucode/intel/000806D1-02
  usr/src/data/ucode/intel/000806EC-04
  usr/src/data/ucode/intel/00090661-01
  usr/src/data/ucode/intel/00090672-01
  usr/src/data/ucode/intel/000906A3-80
  usr/src/data/ucode/intel/000906ED-02
  usr/src/data/ucode/intel/000A0652-20
  usr/src/data/ucode/intel/000A0653-02
  usr/src/data/ucode/intel/000A0655-02
  usr/src/data/ucode/intel/000A0660-80
  usr/src/data/ucode/intel/000A0661-80
  usr/src/data/ucode/intel/000A0671-02
  usr/src/data/ucode/intel/000B0671-02
  usr/src/data/ucode/intel/Makefile.links
  usr/src/pkg/manifests/system-microcode-intel.p5m
Labels: backport-PR

#1271 15175 Update intel CPU Microcode to 20221108 (r151038)
  usr/src/data/ucode/intel/000606C1-10
  usr/src/data/ucode/intel/000706E5-80
  usr/src/data/ucode/intel/000806C1-80
  usr/src/data/ucode/intel/000806D1-02
  usr/src/data/ucode/intel/000806EC-04
  usr/src/data/ucode/intel/00090661-01
  usr/src/data/ucode/intel/00090672-01
  usr/src/data/ucode/intel/000906A3-80
  usr/src/data/ucode/intel/000906ED-02
  usr/src/data/ucode/intel/000A0652-20
  usr/src/data/ucode/intel/000A0653-02
  usr/src/data/ucode/intel/000A0655-02
  usr/src/data/ucode/intel/000A0660-80
  usr/src/data/ucode/intel/000A0661-80
  usr/src/data/ucode/intel/000A0671-02
  usr/src/data/ucode/intel/000B0671-02
  usr/src/data/ucode/intel/Makefile.links
  usr/src/pkg/manifests/system-microcode-intel.mf
  usr/src/test/os-tests/tests/regression/Makefile
Labels: backport-PR

#1280 Upstream merge/2022122601
  usr/src/boot/forth/beadm.4th
  usr/src/boot/forth/support.4th
  usr/src/cmd/pcieadm/pcieadm_cfgspace.c
  usr/src/common/unicode/u8_textprep.c
  usr/src/lib/libc/port/gen/isatty.c
  usr/src/lib/libdladm/Makefile.com
  usr/src/lib/libdladm/common/flowattr.c
  usr/src/lib/libdladm/common/flowprop.c
  usr/src/lib/libdladm/common/libdlaggr.c
  usr/src/lib/libdladm/common/libdlib.c
  usr/src/lib/libdladm/common/libdlstat.c
  usr/src/lib/libdladm/common/linkprop.c
  usr/src/lib/smbsrv/libsmb/Makefile.com
  usr/src/lib/smbsrv/libsmb/common/smb_acl.c
  usr/src/lib/smbsrv/libsmb/common/smb_domain.c
  usr/src/lib/smbsrv/libsmb/common/smb_pwdutil.c
  usr/src/man/man3c/isatty.3c
  usr/src/pkg/manifests/system-test-libctest.p5m
  usr/src/test/libc-tests/runfiles/default.run
  usr/src/test/libc-tests/tests/Makefile
  usr/src/test/libc-tests/tests/isatty.c
Labels: upstream-merge, backport-todo

#1281 15295 SMB services should check IPC caller privileges (r151038)
  usr/src/cmd/idmap/idmapd/idmap_lsa.c
  usr/src/cmd/smbsrv/smbd/smbd_authsvc.c
  usr/src/cmd/smbsrv/smbd/smbd_doorsvc.c
  usr/src/cmd/smbsrv/smbd/smbd_pipesvc.c
  usr/src/cmd/smbsrv/smbd/smbd_share_doorsvc.c
  usr/src/lib/smbsrv/libsmb/common/libsmb.h
  usr/src/lib/smbsrv/libsmb/common/smb_doorclnt.c
Labels: upstream-merge, backport-PR

#1282 15295 SMB services should check IPC caller privileges (r151042)
  usr/src/cmd/idmap/idmapd/idmap_lsa.c
  usr/src/cmd/smbsrv/smbd/smbd_authsvc.c
  usr/src/cmd/smbsrv/smbd/smbd_doorsvc.c
  usr/src/cmd/smbsrv/smbd/smbd_pipesvc.c
  usr/src/cmd/smbsrv/smbd/smbd_share_doorsvc.c
  usr/src/lib/smbsrv/libsmb/common/libsmb.h
  usr/src/lib/smbsrv/libsmb/common/smb_doorclnt.c
Labels: upstream-merge, backport-PR

#1283 15295 SMB services should check IPC caller privileges (r151044)
  usr/src/cmd/idmap/idmapd/idmap_lsa.c
  usr/src/cmd/smbsrv/smbd/smbd_authsvc.c
  usr/src/cmd/smbsrv/smbd/smbd_doorsvc.c
  usr/src/cmd/smbsrv/smbd/smbd_pipesvc.c
  usr/src/cmd/smbsrv/smbd/smbd_share_doorsvc.c
  usr/src/lib/smbsrv/libsmb/common/libsmb.h
  usr/src/lib/smbsrv/libsmb/common/smb_doorclnt.c
Labels: upstream-merge, backport-PR
