Repository omniosorg/illumos-omnios, pull requests merged in 2022-05, with the labels that each got.

#1168 Upstream merge upstream_merge/2022050601
  .gitignore
  README.OmniOS
  usr/src/boot/Makefile.version
  usr/src/cmd/zoneadmd/Makefile
  usr/src/cmd/zoneadmd/vplat.c
  usr/src/cmd/zoneadmd/zoneadmd.c
  usr/src/contrib/zlib/ChangeLog
  usr/src/contrib/zlib/README
  usr/src/contrib/zlib/THIRDPARTYLICENSE
  usr/src/contrib/zlib/THIRDPARTYLICENSE.descrip
  usr/src/contrib/zlib/crc32.c
  usr/src/contrib/zlib/crc32.h
  usr/src/contrib/zlib/deflate.c
  usr/src/contrib/zlib/deflate.h
  usr/src/contrib/zlib/gzguts.h
  usr/src/contrib/zlib/infback.c
  usr/src/contrib/zlib/inffast.c
  usr/src/contrib/zlib/inflate.c
  usr/src/contrib/zlib/inflate.h
  usr/src/contrib/zlib/inftrees.c
  usr/src/contrib/zlib/trees.c
  usr/src/contrib/zlib/zconf.h
  usr/src/contrib/zlib/zlib.h
  usr/src/contrib/zlib/zutil.c
  usr/src/contrib/zlib/zutil.h
  usr/src/pkg/manifests/developer-debug-mdb.p5m
  usr/src/pkg/manifests/system-bhyve-tests.p5m
  usr/src/pkg/manifests/system-kernel-platform.p5m
  usr/src/test/bhyve-tests/runfiles/default.run
  usr/src/test/bhyve-tests/tests/inst_emul/Makefile
  usr/src/test/bhyve-tests/tests/inst_emul/payload_triple_fault.s
  usr/src/test/bhyve-tests/tests/inst_emul/triple_fault.c
  usr/src/test/bhyve-tests/tests/vmm/Makefile
  usr/src/test/bhyve-tests/tests/vmm/interface_version.c
  usr/src/uts/common/fs/lookup.c
  usr/src/uts/common/zmod/THIRDPARTYLICENSE
  usr/src/uts/common/zmod/THIRDPARTYLICENSE.descrip
  usr/src/uts/i86pc/os/cpuid.c
  usr/src/uts/intel/io/vmm/intel/vmx.c
  usr/src/uts/intel/io/vmm/vmm_sol_dev.c
  usr/src/uts/intel/ml/retpoline.s
  usr/src/uts/intel/sys/vmm_dev.h
Labels: upstream-merge

#1172 Update Intel microcode to 20220419 release (r151038)
  README.OmniOS
  usr/src/data/ucode/intel/000506CA-01
  usr/src/pkg/manifests/system-microcode-intel.mf
Labels: backport-PR

#1171 Update Intel microcode to 20220419 release (r151040)
  README.OmniOS
  usr/src/data/ucode/intel/000506CA-01
  usr/src/pkg/manifests/system-microcode-intel.mf
Labels: backport-PR

#1170 Update Intel microcode to 20220419 release (r151042)
  README.OmniOS
  usr/src/data/ucode/intel/000506CA-01
  usr/src/pkg/manifests/system-microcode-intel.p5m
Labels: backport-PR

#1169 Update Intel microcode to 20220419 release
  usr/src/data/ucode/intel/000506CA-01
  usr/src/pkg/manifests/system-microcode-intel.p5m
Labels: backport-todo

#1173 Upstream merge upstream_merge/2022051001
  .gitignore
  usr/src/cmd/perl/Makefile.perl
  usr/src/cmd/perl/Makefile.perl.64
  usr/src/cmd/perl/Makefile.targ
  usr/src/cmd/perl/contrib/Sun/Solaris/BSM/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Intrs/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Intrs/Makefile.com
  usr/src/cmd/perl/contrib/Sun/Solaris/Intrs/amd64/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Intrs/i386/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Intrs/sparc/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Intrs/sparcv9/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Kstat/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Kstat/Makefile.com
  usr/src/cmd/perl/contrib/Sun/Solaris/Kstat/amd64/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Kstat/i386/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Kstat/sparc/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Kstat/sparcv9/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Lgrp/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Lgrp/Makefile.com
  usr/src/cmd/perl/contrib/Sun/Solaris/Lgrp/amd64/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Lgrp/i386/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Lgrp/sparc/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Lgrp/sparcv9/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Pg/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Privilege/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Privilege/Makefile.com
  usr/src/cmd/perl/contrib/Sun/Solaris/Privilege/amd64/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Privilege/i386/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Project/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Project/Makefile.com
  usr/src/cmd/perl/contrib/Sun/Solaris/Project/amd64/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Project/i386/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Project/sparc/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Project/sparcv9/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Task/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Task/Makefile.com
  usr/src/cmd/perl/contrib/Sun/Solaris/Task/amd64/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Task/i386/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Task/sparc/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Task/sparcv9/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Ucred/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Ucred/Makefile.com
  usr/src/cmd/perl/contrib/Sun/Solaris/Ucred/amd64/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Ucred/i386/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Utils/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Utils/Makefile.com
  usr/src/cmd/perl/contrib/Sun/Solaris/Utils/amd64/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Utils/i386/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Utils/sparc/Makefile
  usr/src/cmd/perl/contrib/Sun/Solaris/Utils/sparcv9/Makefile
  usr/src/lib/Makefile.lib
  usr/src/lib/libfru/i386/Makefile
  usr/src/lib/libfru/sparc/Makefile
  usr/src/uts/common/os/bitmap.c
  usr/src/uts/common/sys/bitmap.h
Labels: upstream-merge

#1175 LX: sendfile returns EINVAL at EOF when it should return 0 (r151038)
  README.OmniOS
  usr/src/lib/brand/lx/lx_brand/common/sendfile.c
Labels: backport-PR

#1174 LX: sendfile returns EINVAL at EOF when it should return 0 (r151040)
  README.OmniOS
  usr/src/lib/brand/lx/lx_brand/common/sendfile.c
Labels: backport-PR
