Repository omniosorg/illumos-omnios, pull requests merged in 2022-04, with the labels that each got.

#1144 LX: lx_vdso.so PT_DYNAMIC section should not be writeable (r151038)
  README.OmniOS
  usr/src/lib/brand/lx/lx_vdso/tools/vdso_tool.c
Labels: backport-PR

#1150 Restore early ZONE_ATTR_ values (r151042)
  usr/src/cmd/truss/print.c
  usr/src/uts/common/sys/zone.h
Labels: backport-PR

#1155 Upstream merge/2022040701
  README.OmniOS
  usr/src/uts/common/inet/ip/ipclassifier.c
  usr/src/uts/common/sys/zone.h
  usr/src/uts/i86pc/io/isa.c
  usr/src/uts/i86pc/os/fakebop.c
Labels: upstream-merge

#1162 Pending fixes for new release
  README.OmniOS
  usr/src/cmd/bhyve/pci_xhci.c
  usr/src/lib/lib9p/common/backend/fs.c
  usr/src/lib/lib9p/common/request.c
  usr/src/man/man5/bhyve_config.5
  usr/src/uts/common/brand/lx/syscall/lx_link.c
  usr/src/uts/common/inet/ipf/fil.c
  usr/src/uts/common/inet/ipf/ip_fil_solaris.c
  usr/src/uts/common/inet/ipf/netinet/ip_fil.h
  usr/src/uts/intel/ipf/ipf.global-objs.debug64
Labels: backport-todo

#1163 Pending fixes for new release (r151042)
  usr/src/cmd/bhyve/pci_xhci.c
  usr/src/lib/lib9p/common/backend/fs.c
  usr/src/lib/lib9p/common/request.c
  usr/src/man/man5/bhyve_config.5
  usr/src/uts/common/brand/lx/syscall/lx_link.c
  usr/src/uts/common/inet/ipf/fil.c
  usr/src/uts/common/inet/ipf/ip_fil_solaris.c
  usr/src/uts/common/inet/ipf/netinet/ip_fil.h
  usr/src/uts/intel/ipf/ipf.global-objs.debug64
Labels: backport-PR

#1166 Upstream merge/2022042301
  usr/src/cmd/sgs/common/alist.c
  usr/src/cmd/sgs/common/string_table.c
  usr/src/cmd/sgs/include/sgs.h
  usr/src/cmd/sgs/ld/Makefile.com
  usr/src/cmd/sgs/libld/Makefile.com
  usr/src/cmd/sgs/libld/common/_libld.h
  usr/src/cmd/sgs/libld/common/files.c
  usr/src/cmd/sgs/libld/common/globals.c
  usr/src/cmd/sgs/libld/common/groups.c
  usr/src/cmd/sgs/libld/common/ldmain.c
  usr/src/cmd/sgs/libld/common/libld.msg
  usr/src/cmd/sgs/libld/common/libs.c
  usr/src/cmd/sgs/libld/common/machsym.sparc.c
  usr/src/cmd/sgs/libld/common/map.c
  usr/src/cmd/sgs/libld/common/map_core.c
  usr/src/cmd/sgs/libld/common/map_support.c
  usr/src/cmd/sgs/libld/common/outfile.c
  usr/src/cmd/sgs/libld/common/place.c
  usr/src/cmd/sgs/libld/common/sections.c
  usr/src/cmd/sgs/libld/common/sunwmove.c
  usr/src/cmd/sgs/libld/common/syms.c
  usr/src/cmd/sgs/libld/common/unwind.c
  usr/src/cmd/sgs/libld/common/util.c
  usr/src/cmd/sgs/libld/common/version.c
  usr/src/cmd/sgs/tools/SUNWonld-README
  usr/src/tools/sgs/ld/Makefile
  usr/src/uts/common/io/blkdev/blkdev.c
Labels: upstream-merge
