Repository omniosorg/illumos-omnios, pull requests merged in 2023-03, with the labels that each got.

#1296 14622 want __maybe_unused (r151038)
  usr/src/uts/common/sys/ccompile.h
Labels: backport-PR

#1295 14622 want __maybe_unused (r151042)
  usr/src/uts/common/sys/ccompile.h
Labels: backport-PR

#1305 Upstream merge/2023032401
  usr/src/data/zoneinfo/africa
  usr/src/data/zoneinfo/antarctica
  usr/src/data/zoneinfo/asia
  usr/src/data/zoneinfo/australasia
  usr/src/data/zoneinfo/backward
  usr/src/data/zoneinfo/country.tab
  usr/src/data/zoneinfo/europe
  usr/src/data/zoneinfo/northamerica
  usr/src/data/zoneinfo/southamerica
  usr/src/data/zoneinfo/zone.tab.txt
  usr/src/data/zoneinfo/zone_sun.tab
  usr/src/lib/sun_fc/common/FCHBA.cc
  usr/src/lib/sun_fc/common/FCHBAPort.cc
  usr/src/lib/sun_fc/common/HBANPIVPort.cc
  usr/src/lib/sun_fc/common/HBAPort.cc
  usr/src/lib/sun_fc/common/Sun_fcGetFcpTargetMapping.cc
  usr/src/lib/sun_fc/common/TgtFCHBA.cc
  usr/src/pkg/manifests/system-data-zoneinfo.p5m
Labels: upstream-merge, backport-todo

#1308 Add locking to /usr/lib/rsrvrctl (r151046)
  usr/src/cmd/rsrvrctl/rsrvrctl.c
Labels: backport-PR

#1309 Upstream merge datalink improvements.
  usr/src/cmd/dlmgmtd/dlmgmt_db.c
  usr/src/cmd/dlmgmtd/dlmgmt_door.c
  usr/src/cmd/dlmgmtd/dlmgmt_impl.h
  usr/src/cmd/dlmgmtd/dlmgmt_main.c
  usr/src/cmd/dlmgmtd/dlmgmt_util.c
  usr/src/cmd/zoneadmd/vplat.c
  usr/src/lib/libdladm/common/libdladm.h
  usr/src/lib/libdladm/common/libdlmgmt.c
  usr/src/uts/common/io/dld/dld_drv.c
  usr/src/uts/common/io/dls/dls_mgmt.c
  usr/src/uts/common/os/zone.c
  usr/src/uts/common/sys/dls_mgmt.h
Labels: upstream-merge

#1315 15526 Update tzdata to 2023c (r151046)
  usr/src/cmd/which/Makefile
  usr/src/cmd/which/THIRDPARTYLICENSE
  usr/src/cmd/which/which.c
  usr/src/cmd/which/which.csh
  usr/src/data/zoneinfo/asia
  usr/src/man/man1/which.1
  usr/src/pkg/manifests/system-data-zoneinfo.p5m
Labels: backport-PR

#1314 15526 Update tzdata to 2023c (r151038)
  usr/src/data/zoneinfo/africa
  usr/src/data/zoneinfo/antarctica
  usr/src/data/zoneinfo/asia
  usr/src/data/zoneinfo/australasia
  usr/src/data/zoneinfo/backward
  usr/src/data/zoneinfo/country.tab
  usr/src/data/zoneinfo/etcetera
  usr/src/data/zoneinfo/europe
  usr/src/data/zoneinfo/northamerica
  usr/src/data/zoneinfo/southamerica
  usr/src/data/zoneinfo/zone.tab.txt
  usr/src/data/zoneinfo/zone_sun.tab
  usr/src/pkg/manifests/system-data-zoneinfo.mf
Labels: backport-PR

#1313 15526 Update tzdata to 2023c (r151042)
  usr/src/data/zoneinfo/africa
  usr/src/data/zoneinfo/antarctica
  usr/src/data/zoneinfo/asia
  usr/src/data/zoneinfo/australasia
  usr/src/data/zoneinfo/backward
  usr/src/data/zoneinfo/country.tab
  usr/src/data/zoneinfo/etcetera
  usr/src/data/zoneinfo/europe
  usr/src/data/zoneinfo/northamerica
  usr/src/data/zoneinfo/southamerica
  usr/src/data/zoneinfo/zone.tab.txt
  usr/src/data/zoneinfo/zone_sun.tab
  usr/src/pkg/manifests/system-data-zoneinfo.p5m
Labels: backport-PR

#1312 15526 Update tzdata to 2023c (r151044)
  usr/src/data/zoneinfo/africa
  usr/src/data/zoneinfo/antarctica
  usr/src/data/zoneinfo/asia
  usr/src/data/zoneinfo/australasia
  usr/src/data/zoneinfo/backward
  usr/src/data/zoneinfo/country.tab
  usr/src/data/zoneinfo/europe
  usr/src/data/zoneinfo/northamerica
  usr/src/data/zoneinfo/southamerica
  usr/src/data/zoneinfo/zone.tab.txt
  usr/src/data/zoneinfo/zone_sun.tab
  usr/src/pkg/manifests/system-data-zoneinfo.p5m
Labels: backport-PR

#1311 Upstream merge/2023033001
  usr/src/cmd/which/Makefile
  usr/src/cmd/which/THIRDPARTYLICENSE
  usr/src/cmd/which/which.c
  usr/src/cmd/which/which.csh
  usr/src/data/zoneinfo/asia
  usr/src/man/man1/which.1
  usr/src/pkg/manifests/system-data-zoneinfo.p5m
Labels: upstream-merge, backport-todo
