Repository omniosorg/illumos-omnios, pull requests merged in 2024-05, with the labels that each got.

#1464 Upstream merge upstream_merge/2024050401
  README.OmniOS
  usr/src/cmd/cmd-inet/usr.bin/nc/netcat.c
  usr/src/cmd/cmd-inet/usr.sbin/snoop/snoop_ip.c
  usr/src/cmd/mdb/common/modules/ip/ip.c
  usr/src/cmd/svc/common/notify_params.c
  usr/src/cmd/svc/svccfg/Makefile
  usr/src/cmd/svc/svccfg/svccfg.h
  usr/src/cmd/svc/svccfg/svccfg.y
  usr/src/cmd/svc/svccfg/svccfg_libscf.c
  usr/src/cmd/svc/svccfg/svccfg_main.c
  usr/src/lib/libc/port/locale/strftime.c
  usr/src/man/man1/nc.1
  usr/src/pkg/manifests/system-test-libctest.p5m
  usr/src/test/libc-tests/runfiles/default.run
  usr/src/test/libc-tests/tests/Makefile
  usr/src/test/libc-tests/tests/ascftime.c
  usr/src/test/zfs-tests/tests/functional/cli_root/zfs_property/zfs_written_property_001_pos.ksh
  usr/src/uts/common/fs/zfs/vdev.c
  usr/src/uts/common/fs/zfs/vdev_indirect.c
  usr/src/uts/common/fs/zfs/vdev_label.c
  usr/src/uts/common/inet/ipf/fil.c
  usr/src/uts/common/inet/ipf/ip_proxy.c
  usr/src/uts/common/inet/ipf/netinet/ip_compat.h
Labels: upstream-merge

#1469 Upstream merge/2024051701
  README.OmniOS
  usr/src/boot/Makefile.version
  usr/src/boot/efi/libefi/efi_console.c
  usr/src/boot/efi/loader/framebuffer.c
  usr/src/cmd/fm/modules/common/zfs-retire/zfs_retire.c
  usr/src/cmd/savecore/Makefile
  usr/src/cmd/savecore/savecore.c
  usr/src/cmd/smbsrv/smbd/smbd.h
  usr/src/cmd/svc/svccfg/svccfg.h
  usr/src/common/crypto/sha1/sha1.c
  usr/src/lib/libnvme/common/libnvme_impl.h
  usr/src/lib/libnvme/common/libnvme_log.c
  usr/src/man/man3sec/acl_totext.3sec
  usr/src/man/man4p/tcp.4p
  usr/src/man/man8/zpool.8
  usr/src/pkg/manifests/driver-storage-mpt_sas.p5m
  usr/src/pkg/manifests/system-test-zfstest.p5m
  usr/src/test/crypto-tests/tests/longhash/longhash.c
  usr/src/test/os-tests/tests/tcpsig/tcpsig.c
  usr/src/test/zfs-tests/runfiles/common.run
  usr/src/test/zfs-tests/tests/functional/fault/auto_spare_sorted_001_pos.ksh
  usr/src/uts/common/inet/tcp/tcp_input.c
  usr/src/uts/common/inet/tcp/tcp_opt_data.c
  usr/src/uts/common/inet/tcp/tcp_sig.c
  usr/src/uts/common/inet/tcp/tcp_stats.c
  usr/src/uts/common/inet/tcp_sig.h
  usr/src/uts/common/inet/tcp_stats.h
  usr/src/uts/common/io/clone.c
  usr/src/uts/common/io/fibre-channel/fca/qlc/ql_fm.c
  usr/src/uts/common/io/ptem.c
  usr/src/uts/common/io/scsi/adapters/lmrc/lmrc.c
  usr/src/uts/common/io/scsi/adapters/lmrc/lmrc.h
  usr/src/uts/common/io/scsi/adapters/lmrc/lmrc_ddi.c
  usr/src/uts/common/io/scsi/adapters/lmrc/lmrc_ioctl.c
  usr/src/uts/common/io/scsi/adapters/lmrc/lmrc_ioctl.h
  usr/src/uts/common/io/scsi/adapters/lmrc/lmrc_phys.c
  usr/src/uts/common/io/scsi/adapters/lmrc/lmrc_phys.h
  usr/src/uts/common/io/scsi/adapters/lmrc/lmrc_raid.c
  usr/src/uts/common/io/scsi/adapters/lmrc/lmrc_raid.h
  usr/src/uts/common/io/scsi/adapters/lmrc/lmrc_reg.h
  usr/src/uts/common/io/scsi/adapters/lmrc/lmrc_scsa.c
  usr/src/uts/common/io/scsi/adapters/mpt_sas/mptsas.c
  usr/src/uts/common/io/scsi/adapters/mpt_sas/mptsas_impl.c
  usr/src/uts/common/io/scsi/adapters/mpt_sas/mptsas_init.c
  usr/src/uts/common/io/vioif/vioif.c
  usr/src/uts/common/sys/scsi/adapters/mfi/mfi.h
  usr/src/uts/common/sys/scsi/adapters/mfi/mfi_bbu.h
  usr/src/uts/common/sys/scsi/adapters/mfi/mfi_evt.h
  usr/src/uts/common/sys/scsi/adapters/mfi/mfi_ioctl.h
  usr/src/uts/common/sys/scsi/adapters/mfi/mfi_ld.h
  usr/src/uts/common/sys/scsi/adapters/mfi/mfi_pd.h
  usr/src/uts/common/sys/scsi/adapters/mpi/mpi2_cnfg.h
  usr/src/uts/common/sys/scsi/adapters/mpt_sas/mptsas_var.h
  usr/src/uts/common/sys/scsi/targets/stdef.h
  usr/src/uts/intel/clone/Makefile
Labels: upstream-merge, backport-todo

#1470 16350 SHA1 may produce incorrect hashes if given a 2^29 byte input (r151050)
  usr/src/common/crypto/sha1/sha1.c
  usr/src/test/crypto-tests/tests/longhash/longhash.c
Labels: backport-PR

#1471 16350 SHA1 may produce incorrect hashes if given a 2^29 byte input (r151048)
  usr/src/common/crypto/sha1/sha1.c
  usr/src/test/crypto-tests/tests/longhash/longhash.c
Labels: backport-PR

#1472 16350 SHA1 may produce incorrect hashes if given a 2^29 byte input (r151046)
  usr/src/common/crypto/sha1/sha1.c
  usr/src/test/crypto-tests/tests/longhash/longhash.c
Labels: backport-PR

#1480 Upstream merge/2024053001
  README.OmniOS
  usr/src/cmd/truss/Makefile
  usr/src/cmd/truss/codes.c
  usr/src/cmd/truss/codes.h
  usr/src/cmd/truss/codes_bhyve.c
  usr/src/lib/libc/port/gen/memalign.c
  usr/src/lib/libtermcap/Makefile
  usr/src/lib/libtermcap/common/xtermcap.h
  usr/src/lib/libumem/common/umem.c
  usr/src/man/man3c/aligned_alloc.3c
  usr/src/pkg/manifests/system-header.p5m
  usr/src/pkg/manifests/system-test-libctest.p5m
  usr/src/test/libc-tests/runfiles/default.run
  usr/src/test/libc-tests/tests/Makefile
  usr/src/test/libc-tests/tests/aligned_alloc.c
  usr/src/test/libc-tests/tests/aligned_alloc.ksh
  usr/src/test/os-tests/tests/fifo-tvnsec.c
  usr/src/uts/common/brand/lx/sys/lx_fcntl.h
  usr/src/uts/common/brand/lx/syscall/lx_fcntl.c
  usr/src/uts/common/inet/ip/icmp.c
  usr/src/uts/common/inet/udp/udp.c
  usr/src/uts/common/io/blkdev/blkdev.c
  usr/src/uts/common/io/nvme/nvme.c
  usr/src/uts/common/io/nvme/nvme_var.h
  usr/src/uts/common/sys/blkdev.h
Labels: upstream-merge, backport-todo
